### ISSUE TITLE
default transforming html

### ISSUE THREAD

**Issue by PaulWieland** [michelf/php-markdown#104]
My understanding is that this should work:

```
Markdown::defaultTransform('<p>a</p>
<p>b</p>
<p>c</p>');
```

Should output:

```
<p>a</p>
<p>b</p>
<p>c</p>
```

This is verified by gruber's online dingus.

Instead it outputs:

```
<p>a</p>

<p><p>b</p>
<p>c</p></p>
```

**Comment by Avalarion** [comment]
Please use CodeFormatition^^. I am not able to see a difference.

**Comment by PaulWieland** [comment]
My tabs did not paste, I reformatted with spaces, so the code blocks should work now.

**Comment by michelf** [comment]
If you write this instead it'll pass with no problem:

```
<p>
a
</p>
```

But I think this deserves to be corrected nonetheless. Note that the MarkdownExtra parser does not have this problem.

**Comment by michelf** [comment]
Oops. I meant you if you write this it'll pass:

```
<p>a</p>

<p>b</p>

<p>c</p>
```

The blank lines before and after each paragraph make it conforms with [the syntax description](http://daringfireball.net/projects/markdown/syntax#html) which says:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

**Comment by PaulWieland** [comment]
Interesting note on the syntax description. If you test on the dingus you'll see it works there, which is odd.

**Comment by PaulWieland** [comment]
Using markdownExtra solved my problem, so thank you for that tip!
