### ISSUE TITLE
How to solve XSS problem in better way?

### ISSUE THREAD

**Issue by allenhsu** [michelf/php-markdown#106]
I'm working on a project whose contents are generated by users. So XSS should be taken care of. With code similar to the following one, users can generate a javascript link, which causes XSS problems.

```
[Link](javascript:alert('XSS'))
```

How can I prevent XSS problem in a better way?

BTW, is there any way to configure which tags are supported?

**Comment by michelf** [comment]
Use a separate XSS filter.
http://michelf.ca/blog/2010/markdown-and-xss/

There's no way to configure which tags are allowed and which are not in the Markdown parser. But if you use a good XSS filter you should be able to whitelist permissible tags, and attributes.

**Comment by allenhsu** [comment]
Thanks, according to the blog, I'll give `kses` a try. I've also found htmlpurifier.org
