### ISSUE TITLE
Footnote link placement affects Image tag processing

### ISSUE THREAD

**Issue by minchinweb** [michelf/php-markdown#123]
I'm using Markdown Extra version 1.2.7.

This is the markdown source file:

> # Image Test [^12]
> 
> ![1800 Travel][img6]
> ![1830 Travel][img7]
> 
> [img6]: images/MGR-1800-travel.jpeg "Travel Speeds in 1800"
> [^12]: [Mother Nature Network](http://www.mnn.com/green-tech/transportation/stories/how-fast-could-you-travel-across-the-us-in-the-1800s)
> [img7]: images/MGR-1830-travel.jpeg "Travel Speeds in 1830"

However, the image liked to above the footnote is processed correctly, but the image linked to below the footnote is not processed. If I add a line between the [^12] and [img7] line, it will also work again.

Output of above markdown source:
![image-test](https://f.cloud.github.com/assets/1548809/975788/e74db2e4-067f-11e3-8694-c37c60783af4.png)

**Comment by michelf** [comment]
Hum, you're right. It shouldn't behave this way. I'll fix this eventually, meanwhile you can put an extra blank line after the footnote to fix things.
