### ISSUE TITLE
Remove $this->in_anchor 

### ISSUE THREAD

**Issue by yuanzhou** [michelf/php-markdown#125]
`$this->in_anchor` is used as a status flag to avoid invalid nesting in `doAnchors()`. The problem I see is this variable does nothing.

**Comment by michelf** [comment]
What do you mean by "this variable does nothing", you've just explained what it does.

**Comment by yuanzhou** [comment]
Here is my understanding:

```
protected function doAnchors($text) {
    if ($this->in_anchor) return $text;
    $this->in_anchor = true;

    // code

    $this->in_anchor = false;
    return $text;
}
```

By default, `$this->in_anchor` is defined as protected and it's set to false, so this function will never change the value of `$this->in_anchor`.

**Comment by michelf** [comment]
But note that this function is called recursively when processing the textual content of the link. See the call to `$this->runSpanGamut($link_text)` in the two callbacks below it, which, in turn, will call `doAnchor` again.

**Comment by yuanzhou** [comment]
Got it. Thanks a lot for the explanation. I had this question when I thought to change `$in_anchor` to a local variable. Now I'll put it back as a class property.

**Comment by michelf** [comment]
You're welcome.
