### ISSUE TITLE
can't disable html markup at all

### ISSUE THREAD

**Issue by shukebeta** [michelf/php-markdown#13]
I have already set the property
 $no_markup = true;
 $no_entities = true;

**Comment by shukebeta** [comment]
my testing text:
&lt;script&gt;alert('hello,world');&lt;/script&gt;

BTW: I'm using the newest php markdown extra 1.2.5

**Comment by michelf** [comment]
I haven't tried to replicate this yet. I will.

But following up on your example, I need to point out that even when it works correctly the no markup and no entity mode can still let javascript through (as a link or image URL for instance). You need something much more specialized than that to prevent nefarious users from adding javascript to the content. Read [Markdown and XSS](http://michelf.com/weblog/2010/markdown-and-xss/) for more details.

**Comment by michelf** [comment]
Fixed in the extra branch. Thanks for reporting this.
