### ISSUE TITLE
Please clarify Version

### ISSUE THREAD

**Issue by remicollet** [michelf/php-markdown#137]
Hi,

Archive name is 1.4.0
Archive content is "PHP Markdown Lib 1.2.8"

Can you please explain ?

**Comment by michelf** [comment]
You've got the correct version, the folder is just improperly labelled. I've fixed it. Thanks.

There is actually no version 1.2.8 for PHP Markdown Lib. That's an error of my packaging script that took the version number for the corresponding classic PHP Markdown Extra package instead.
