### ISSUE TITLE
Em dashes?

### ISSUE THREAD

**Issue by russellbits** [michelf/php-markdown#144]
Did I just make this up or isn't markdown meant to convert "--" to &emdash?

I can't find that in the syntax documentation, and the library isn't doing the conversion.

**Comment by michelf** [comment]
That's not a feature of Markdown. You have to chain the filter with [SmartyPants](/michelf/php-smartypants). For instance:

```
use \Michelf\Markdown, \Michelf\SmartyPants;
$my_html = Markdown::defaultTransform($my_text);
$my_html = SmartyPants::defaultTransform($my_html);
```
