### ISSUE TITLE
[feature request] Markdown Extra vs Dotclear syntax

### ISSUE THREAD

**Issue by franck-paul** [michelf/php-markdown#146]
Hi,

I wrote a comparison (http://open-time.net/post/2014/01/09/Markdown-vs-Wiki-Dotclear, in french) between the MD extra syntax and the syntax of Dotclear wiki (french blogging software). It seems that the MD extra is near to be a perfect wiki syntax, may be with the following suggestions:

I would like to suggest you 4 additions to your syntax:
1. ++ <text> ++ giving <ins> text </ins>, for additions
2. -- <text> -- giving <del> text </del>, for deletions
3. ~ <anchor> ~ giving <a name="anchor"></a>, for anchors
4. {{ <inline quote> }} giving <q> inline quote </q>, for inline quote

It should be nice also to be able to precise the language of URL as I often insert such (english) links in my french posts.

Have you any comments about this?

Regards

(I'm the lead dev of the Dotclear project)

**Comment by michelf** [comment]
`--` for `<del>` won't fly. `--` is already used by too many people to write em-dashes. While this is not directly part of Markdown, it's part of [SmartyPants](http://github.com/michelf/php-smartypants/) which is very often used in conjunction with Markdown.

It'd be strange to offer `++` without `--`.

In your post, you're saying that Markdown Extra has nothing for anchors. While it's technically true you can't make a `<a anchor="blah">` element without typing it all, you can give an `id` attribute to a couple of Markdown elements such as headers, images, links, and code blocks, which fulfills the same role. See [special attributes](http://michelf.ca/projects/php-markdown/extra/#spe-attr) in the spec.

As for inline quotes inside a `<q>` element, that's something I don't get. `<q>` looks good in theory, but it's a mess to style correctly when you consider all the different quoting styles between languages. I'm happy not having HTML elements for sentences, conditional clauses, etc, so I don't get why we need one for quotes. I'm not a fan of replacing punctuation with tags. That said, if you want smart punctuation (without `<q>`), I'll refer you again to [SmartyPants](http://github.com/michelf/php-smartypants/).

I'm not sure which syntax should be used for `hreflang` in links. That's something I'd like to have too actually. That said, feel free to link to the [documentation in french](http://michelf.ca/projets/php-markdown/extra/) if you're writing a French post. This way you won't need `hreflang`. ;-)

---

From your post:

> Autre petit inconvénient, l’utilisateur est tenu de fournir des références de note unique avec Markdown

Footnote ids need to be unique only within the same Markdown document. If you put multiple Markdown posts in the same HTML document you should invoke the parser by [setting a different footnote id prefix](http://michelf.ca/projects/php-markdown/configuration/#markdown-extra) for each post so they don't clash together when on the same page. I don't know if Dotclear does that, I'm mentioning it in case you don't already know.

**Comment by franck-paul** [comment]
You're right for --, your SmartyPants lib (which I also used in a Dotclear plugin) already used it. And then offering ++ without -- might be curious.

You're also right for anchor as there is another way to insert them in a Markdown written post.

About `<q>` I'm not wondering if we need to propose it or not, as it exists and used (by me and by others). Anyway, it's not really a pain to insert `<q>` instead of {{. The "styles" of quotes should be relevant to the language specified, it's true, and this should be cope by the browser as soon as you specify the language, isn't it?

In the Dotclear syntax each footnote has a unique id, so we have not to cope with potential collision even with more than one post in a page. I will have to check our implementation of your MD lib in Dotclear to be sure that will not encounter such problems.

Thank's a lot for your comments about my suggestions.

**Comment by franck-paul** [comment]
I think that we can close this issue now :-)
