### ISSUE TITLE
There is a code tag inside the pre tag (bug?)

### ISSUE THREAD

**Issue by powder96** [michelf/php-markdown#15]
It is not necessary to put tag &lt;code&gt; into &lt;pre&gt; one. Also, it does not look good with some stylesheets, like Twitter Bootstrap.

**Comment by michelf** [comment]
Actually, this is how the HTML 5 spec says it should be done:
http://www.w3.org/TR/html5/grouping-content.html#the-pre-element

> To represent a block of computer code, the pre element can be used with a code element; to represent a block of computer output the pre element can be used with a samp element. Similarly, the kbd element can be used within a pre element to indicate text that the user is to enter.

If a stylesheet cannot handle it, the stylesheet should be fixed.

**Comment by powder96** [comment]
Yes, that was a bug in Twitter Bootstrap. It is fixed now in v2.0.1-wip.
