### ISSUE TITLE
Fenced Code Blocks producing <p><code> instead of <pre><code>

### ISSUE THREAD

**Issue by funnylookinhat** [michelf/php-markdown#152]
``````
```
if( this == that ) 
    echo 'Yes';
else
    echo 'No way.';
```
``````

Produces the following:

```
<p><code>if( this == that ) 
    echo 'Yes';
else
    echo 'No way.';</code></p>
```

I'm not sure why - because looking at the code it seems as though it should do 

```
<pre><code>
```

https://github.com/michelf/php-markdown/blob/lib/Michelf/Markdown.php#L2808-L2828

Sorry if I'm missing something here :)

**Comment by vagari** [comment]
Are you using regular Markdown? Markdown Extra has the fenced code blocks. Regular Markdown uses indents to designate a code block. Try it in [the dingus](http://michelf.ca/projects/php-markdown/dingus/).

```
    if( this == that ) 
         echo 'Yes';
    else
        echo 'No way.';
```

versus...

``````
```
if( this == that ) 
     echo 'Yes';
else
    echo 'No way.';
```
``````

**Comment by michelf** [comment]
@vagari is right. If you're not using the Extra parser (which supports fenced code block), then

``````
```something```
``````

just denotes a regular code span. That code span gets wrapped in a paragraph later because it's a span-level element.

**Comment by funnylookinhat** [comment]
Ah geez - you're right.  I had assumed that Markdown:: would do the trick given that the code was in Markdown.php - my bad!  Thanks for the help.
