### ISSUE TITLE
[Bug] Markdown wraps paragraphs in paragraphs

### ISSUE THREAD

**Issue by michael-e** [michelf/php-markdown#158]
There is a bug in the "pure Markdown" transformation.

Consider the following input:

```
<p>Hello</p>
<p>Michael</p>
<p>E.</p>
```

Using `Markdown`, this is the result:

```
<p>Hello</p>

<p><p>Michael</p>
<p>E.</p></p>
```

Using `Markdown Extra`, however, the result is correct (i.e. the HTML syntax is unchanged):

```
<p>Hello</p>

<p>Michael</p>

<p>E.</p>
```

The issue can be replicated on the Dingus page.

**Comment by michelf** [comment]
The pure Markdown parser wants you to follow the rule found in the Markdown Syntax document:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

http://daringfireball.net/projects/markdown/syntax/#html

So if you do this, it'll work:

```
<p>Hello</p>

<p>Michael</p>

<p>E.</p>
```

**Comment by michelf** [comment]
Hum, I see that it works with Markdown.pl though (tested on the [dingus](http://daringfireball.net/projects/markdown/dingus)). It should probably work here too in this case. I'll have to look into this.

**Comment by michael-e** [comment]
> it works with Markdown.pl

I was just about to write this. :-)

Regarding John Gruber's Markdown syntax document: I always thought that "surrounding content" means non-HTML content (like given in the example), so pure HTML wouldn't  need to be formatted in a special way in order to remain intact. (Wouldn't  this be against the spirit of Markdown, somehow?)

Thanks for looking into it! (Should you find a simple "quick fix", it would be great to know about it. It could save me a lot of time.)

**Comment by michael-e** [comment]
Obviously this has been solved. I can not replicate the problem with 1.8.0. Closing the issue!
