### ISSUE TITLE
Fatal error: Class 'Markdown' not found 

### ISSUE THREAD

**Issue by g-liu** [michelf/php-markdown#162]
I'm using php-markdown via `require_once` mode.

At the top of my `index.php` I have `require_once 'Michelf/Markdown.inc.php';`. I checked the directory and file and they're all there

I try to call something as simple as:

```
echo Markdown::defaultTransform("hi");
```

and it says

```
Fatal error: Class 'Markdown' not found in /var/www/path/to/index.php on line 36
```

What's going on?

**Comment by michelf** [comment]
The `Markdown` class is in the `Michelf` namespace. So you have to write the namespace too when accessing the class by writing `\Michelf\Markdown`. Alternatively, you can create an alias with the `use` keyword to avoid having to write the namespace part all the time. For reference: http://php.net/manual/en/language.namespaces.php

Does this answer your question?

**Comment by ethaniel** [comment]
In case someone else finds this. Here is an example how it should be:
```
require_once 'Michelf/Markdown.inc.php';
echo \Michelf\Markdown::defaultTransform("hi");
```
