### ISSUE TITLE
Random text creates empty output

### ISSUE THREAD

**Issue by markseuffert** [michelf/php-markdown#174]
Hi,

I was testing latest Markdown library together with @wunderfeyd. With random text as input it happens sometimes that there's no output, just a newline. I tried to isolate the problem, but didn't find out that much. It happens in the Markdown Extra parser and around 14K of random input text. 

```
use \Michelf\MarkdownExtra;
$my_html = MarkdownExtra::defaultTransform($my_text);
```

There was no problem with normal Markdown parser and regular text bigger than 14K.
Is there a way to get debugging output.... someone wants to have a look at our input files?

**Comment by markseuffert** [comment]
Here's a test file https://github.com/wunderfeyd/yellowcms-tests/blob/master/zzz-random2.txt

I used PHP 5.5 with
pcre.backtrack_limit => 1000000 => 1000000
pcre.recursion_limit => 100000 => 100000

**Comment by jaswrks** [comment]
This happens to me in v1.5.0 using PHP Markdown Extra with the following:

``` markdown
## Header {#my-header .my-class}
```

Removing `#my-header` or `.my-class` will correct this. Leaving them both together results in everything being eaten for some reason; i.e., I get back an empty string.

**Comment by michelf** [comment]
@jaswsinc Can you tell me more about your PHP configuration (version, and the `pcre.backtrack_limit` and `pcre.recursion_limit` settings)?

It works fine for me on [the dingus](https://michelf.ca/projects/php-markdown/dingus/).
