### ISSUE TITLE
Plugin interface for WordPress no longer accessible

### ISSUE THREAD

**Issue by loisaidasam** [michelf/php-markdown#177]
http://michelf.ca/projects/php-markdown/classic/

```
$ curl http://michelf.ca/projects/php-markdown/classic/
curl: (6) Couldn't resolve host 'michelf.ca'
```

:see_no_evil:

**Comment by michelf** [comment]
The site had a few minutes of downtime today. Is it working for you now?

**Comment by loisaidasam** [comment]
Looks to be back, thanks @michelf :+1:
