### ISSUE TITLE
HTML5 trend. Is it time to change defaul $empty_element_suffix to " >" ?

### ISSUE THREAD

**Issue by jesus2099** [michelf/php-markdown#181]
Hello,
I have been using PHP Markdown (as part of **Hello! CMS J2 FIX**) for so long time now.

I have been using it in [HTML 4.01 setting](https://github.com/michelf/php-markdown/blob/a8c56ecd5e9e7c7d37d00c814c864c3bc8b32694/Michelf/Markdown.php#L51) :

```
public $empty_element_suffix = " >";
```

I’m not sure what syntax is officially more prominently supported now by php-markdown (#58)… you can close this ticket as invalid if it’s still XHTML. :)

**Comment by jesus2099** [comment]
Uh oh, I’ve just noticed that there is now a new version called **lib** and that I was using the **classic** version*… And in that new version doc, it’s already mentionned that

> **empty_element_suffix = " />"**
> This is the string used to close tags for HTML elements with no content such as `<br>` and `<hr>`. The default value creates XML-style empty element tags **which are also valid in HTML 5.**

So that closes my ticket, sorry again.

(*) it seems I only need to change my include if I want to migrate to lib version, isn’t it ?

**Comment by michelf** [comment]
> it seems I only need to change my include if I want to migrate to lib version, isn’t it ?

The lib version uses a different class name for the parser and no longer provides a global `Markdown` function. The parser class is mostly the same though. Take a look at the Readme file for details.
