### ISSUE TITLE
Space before converting underscore to <em>

### ISSUE THREAD

**Issue by ghost** [michelf/php-markdown#183]
Php markdown converts smthing like emoji `:small_blue_diamond:` to `:small<em>blue</em>diamond:`. It would be better if it check for a space before underscore smthing like `space_blue_space` before modifying it with `<em>`.

**Comment by michelf** [comment]
This is intended behaviour. Well, not in your case but in the original Markdown syntax you can use `_` for intra-word emphasis.

I'd suggest you use the Markdown Extra parser which does not have this behaviour.

**Comment by ghost** [comment]
Thanks. It's working.
