### ISSUE TITLE
change internal link definition

### ISSUE THREAD

**Issue by flashpixx** [michelf/php-markdown#188]
Hello,

I use the Markdown parser in a complex plugin structure, so within the plugin I generate HTML code with the parser and after the HTML code is generated, I send it to the rendering component of my CMS.

If I define in a Markdown document an internal link

``` markdown
[internal link](documentfile)
```

The parser generates an URL like

```
http://server/plugin/pluginname/documentfile
```

but in my case I need a structure with a GET parameter like

```
http://server/plugin/pluginname/render?md=documentfile
```

because the URL (part before ?) is be fixed by the CMS.

How can I change the behavior of build internal links?

**Comment by michelf** [comment]
There is a `url_filter_callback` configuration variable that was added recently for purposes like this one. It's not yet in the official release; it's currently sitting on the `lib` branch and it'll be in the next release (I have yet to write the documentation). The callback function takes one URL parameter and the returned value becomes the new URL. Note that you'll need to detect yourself when a link is an internal link within the callback.

**Comment by flashpixx** [comment]
Does this work this also with images?
So I will wait 'till the next release
Thanks

**Comment by michelf** [comment]
Yes, it works with images too. Everywhere there's a URL.

**Comment by flashpixx** [comment]
The `url_filter_func` call works well, I have tested it with images and documents.

Can I use this also for `a tag` calls, I would like to define tags with `[mytag](#mytag)` and the href call with `[tag description](document#mytag)`. The `url_filter_func` modifies the link only, so I need to modify the html result. How can I do this?

**Comment by michelf** [comment]
With Markdown Extra you can write

```
Header   {#some-id}
```

which will put the `id="some-id"` attribute on the header. If you want those generated automatically, you can only hack the code currently.

Sorry for the late reply.
