### ISSUE TITLE
underscored_text_gets_emphasised 

### ISSUE THREAD

**Issue by sudoaza** [michelf/php-markdown#19]
text like that ends up with an <em> which breaks links, i've fixed this by changing line 1149 (makeCodeSpan) added \b (word boundary) to the regex

```
1145 
1146     var $em_relist = array(
1147         ''  => '(?:(?<!\*)\*(?!\*)|(?<!_)_(?!_))(?=\S)(?![.,:;]\s)',
1148         '*' => '(?<=\S)(?<!\*)\*(?!\*)',
1149         '_' => '(?<=\S)(?<!_)\b_(?!_)',
```

**Comment by sudoaza** [comment]
``` php

1145 
1146     var $em_relist = array(
1147         ''  => '(?:(?<!\*)\*(?!\*)|(?<!_)_(?!_))(?=\S)(?![.,:;]\s)',
1148         '*' => '(?<=\S)(?<!\*)\*(?!\*)',
1149         '_' => '(?<=\S)(?<!_)\b_(?!_)',
```

**Comment by michelf** [comment]
That's actually a feature of Markdown. I'm not going to change the behaviour because I want to keep compatibility with other implementations, especially the reference implementation by John Gruber. But you can use PHP Markdown Extra instead, which does not does not treat underscores in the middle of a word as emphasis markers.

**Comment by ghost** [comment]
@rata0071 and @michelf : Unless I am missing your point, you can always use a backslash to escape characters that might otherwise be rendered as Markdown code.

For example: `This\_is\_markdown` renders as `This_is_markdown`

Or am I missing something?

**Comment by michelf** [comment]
@geekpanth3r True, you can use a backslash to escape the underscore also.

And rereading the initial issue by @rata0071, perhaps I should have mentioned that Markdown has a URL link syntax consisting of putting angle brackets around a URL (`<http://example.com>`) which won't apply emphasis to links. That's assuming you want the URL be be a link.

**Comment by sudoaza** [comment]
@geekpanth3r & @michelf thanks but i was after something really transparent for the user and simple. php-markdown was the closest but i made some minor changes to fit my needs, This undersocre thing, urls to link and xss filtering. Check it :P http://esfriki.com
