### ISSUE TITLE
strip out markdown?

### ISSUE THREAD

**Issue by bhhaskin** [michelf/php-markdown#190]
Does php-markdown have the ability to strip out markdown?

e.g. Using php-markdown in WordPress headings.  So when using the heading in the title tag the markdown can be removed for proper display, but in the page it self markdown is rendered.

**Comment by michelf** [comment]
Wouldn't filtering normally and then calling `strip_tags` on the HTML result do the job?

**Comment by bhhaskin** [comment]
I suppose that would work...
