### ISSUE TITLE
Link in header isn't converted correctly when there is space in the address

### ISSUE THREAD

**Issue by annando** [michelf/php-markdown#192]
See this code:

```
### [Title](http://domain.tld/ )
```

It is converted to:

```
<h3>[Title](<a href="http://domain.tld/">http://domain.tld/</a> )</h3>
```

It works when the space is removed:

```
### [Title](http://domain.tld/)
<h3><a href="http://domain.tld/">Title</a></h3>
```

**Comment by annando** [comment]
Update: I just saw that the space at the end is always a problem - not only in headers.

**Comment by auge8472** [comment]
The space is _the_ problem because it doesn't satisfy the syntax rules.

**Comment by annando** [comment]
Problem is that the people from Diaspora are generating their links this way.

**Comment by michelf** [comment]
@annando I'm not sure how you get this result. Which version are you using? If I try on the PHP Markdown Dingus I get a link just fine:
https://michelf.ca/projects/php-markdown/dingus/

@auge8472 The syntax rules aren't clear on details like that. But I think it should be supported since it seem already to work [pretty much everywhere](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5BTitle%5D%28http%3A%2F%2Fdomain.tld%2F+%29).

**Comment by annando** [comment]
Ooops ... sorry. I had opened several github pages. I just realized that I had this effect with another project ... I was comparing several projects and I'm unsure which one to take.

**Comment by annando** [comment]
I like the reactions here. So I guess I will use this library and not the other one. In the past we already used the old version, so I hope we won't be disappointed at our project.

**Comment by auge8472** [comment]
@michelf Maybe the rules don't forbid it, but every description i found came without trailing spaces. So my assumption was, that this is not part of the rules.

And, to speak about "pretty much everywhere". At the linked page only one service generates a valid link. But I got only three results. One as valid link, one with a linked URL inside the Parentheses and one with a non linked URL in Parentheses. It's a bit confusing.

**Comment by michelf** [comment]
>  But I got only three results. [...] It's a bit confusing.

You are reading the page wrong. Babelmark 2 groups identical results together. Implementations generating the same output are listed beside the ouptput, and there's about 20 of them generating a correct link.

> every description i found came without trailing spaces

Markdown descriptions tell you what to write to produce a given output, not how to parse things for which there are no examples in the description. Note that there is a space between the URL and the title when you have a title. Whether that space is still allowed when you have no title could be debated. PHP Markdown is mimicking what the original Markdown implementation has chosen to do, and I see no reason why to do things differently than others.

If you want a formal definition that explicitly mentions the space, you can look at the [CommonMark spec](http://spec.commonmark.org/0.16/#inline-link).

**Comment by scux** [comment]
I you try on https://michelf.ca/projects/php-markdown/dingus/

```
 - [link](http://xxx/filename.pdf)
 - [link](http://xxx/filename with spaces.pdf)
```

You get

```
<ul>
<li><a href="http://xxx/filename.pdf">link</a></li>
<li>[link](http://xxx/filename with spaces.pdf)</li>
</ul>
```

There's the problem.

**Comment by michelf** [comment]
@scux I don't think it is wrong to reject the link in this case. Also note that you can surround the URL in `<`angle brackets`>` to make it accept the space. If you want to discuss this further, please open a new issue.
