### ISSUE TITLE
Blockquote before a link isn't converted correctly

### ISSUE THREAD

**Issue by annando** [michelf/php-markdown#193]
See this code:

```
<br><a href="http://www.heise.de/newsticker/meldung/NSA-Skandal-Snowden-Doku-Citizenfour-mit-Oscar-ausgezeichnet-2557279.html" target="_blank">NSA-Skandal: Snowden-Doku "Citizenfour" mit Oscar ausgezeichnet</a><blockquote>23.02.2015 07:07 Bei der Oscar-Verleihung ist der Dokumentarfilm "Citizenfour" &uuml;ber die NSA-Enth&uuml;llungen des Edward Snowden als bester Dokumentarfilm ausgezeichnet worden.
```

This converted to this code:

```
[NSA-Skandal: Snowden-Doku "Citizenfour" mit Oscar ausgezeichnet](http://www.heise.de/newsticker/meldung/NSA-Skandal-Snowden-Doku-Citizenfour-mit-Oscar-ausgezeichnet-2557279.html)> 23.02.2015 07:07 Bei der Oscar-Verleihung ist der Dokumentarfilm "Citizenfour" über die NSA-Enthüllungen des Edward Snowden als bester Dokumentarfilm ausgezeichnet worden.
```

Problem is that my tested markdown browsers don't recognized the ">" character as start of a quote because there is no newline before it.

**Comment by michelf** [comment]
I'm a little confused. Are you sure those samples shouldn't have two lines? Also, the first is the output and the second is the input, right?

**Comment by annando** [comment]
I'm confused as well ... I just did the same mistake like yesterday. This time I mixed your library with this one: https://github.com/nickcernis/html-to-markdown

I really should be more concentrated :)
