### ISSUE TITLE
Problem with unbalanced HTML elements

### ISSUE THREAD

**Issue by annando** [michelf/php-markdown#194]
This time this issue really is meant for this library :)

I have this line consisting of a mixture of markdown and HTML elements:

```
<p>First **line**<p>Second *line*<p>Third line
```

This converted this way:

```
<p>&lt;</p>

<p>p>First <strong>line</strong></p>

<p>&lt;</p>

<p>p>Second <em>line</em></p>

<p>&lt;</p>

<p>p>Third line</p>
```

The parser works correctly if the paragraphs would be balanced:

```
<p>First **line**</p><p>Second *line*</p><p>Third line</p>
```

I know that this is some failure within the input. Problem is: I can't change that. I'm using this library to parse data from Diaspora. The people there will not change something that is working there (although it maybe partially wrong)

If you want to test it with the original source you can take the markdown from here:
https://pod.geraspora.de/posts/2eaf9d609da701329e654860008dbc6c.xml (the stuff inside the "raw_message" elements)

The Diaspora parser is parsing it this way:
https://pod.geraspora.de/posts/2eaf9d609da701329e654860008dbc6c

**Comment by annando** [comment]
BTW: I just saw that this line isn't parsed correctly as well:

```
<p>First **line**</p><p>Second *line*</p><p>Third line</p>
```

The markdown inside the parapgraphs isn't converted:

```
<p>First **line**</p>

<p>Second *line*</p>

<p>Third line</p>
```

**Comment by michelf** [comment]
> I know that this is some failure within the input. Problem is: I can't change that.

You are welcome to propose a pull request to fix that. I know it is suboptimal, but this isn't going to be a priority anytime soon. (

> The markdown inside the parapgraphs isn't converted:

This is intended. The [Markdown syntax rules](https://daringfireball.net/projects/markdown/syntax#html) has this to say:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style `*emphasis*` inside an HTML block.

With Markdown Extra you can add a `markdown="1"` attribute to process the content as Markdown, but I don't think that'll help you much if you're parsing someone else's Markdown source destined for another parser. Perhaps you should use the parser Diaspora is using instead.

**Comment by annando** [comment]
I can fix the unbalanced html elements with only a few lines of code. I just have to load the content into the XML-DOM and save it from there.

I will try it with this attribute, thanks!

I can't use the parser that Diaspora is using since Diaspora isn't coded in PHP. But this parser is mostly compatible to the Markdown they are using. We used an old version of your library for years now and it mostly worked.

**Comment by annando** [comment]
I just tested it. It seems to work (partly). There is now only a single problem left. I replaced the `<p>` with `<p markdown="1">` and it gets parsed. But: linebreaks inside these elements aren't parsed. I will try to code some workaround for that if this is an expected behaviour.

**Comment by auge8472** [comment]
@annando what do you mean with the following sentence?

> But: linebreaks inside these elements aren't parsed.

Do you speak about a HTML-linebreak `<br>` or about a linefeed (`LF` or `CRLF`)? In the latter case the linebreak is present in the source code, but HTML works as intended and shows it as a whitespace (as spaces, tabs …).

**Comment by annando** [comment]
I had several problems and tried different solutions. Now I simply replace all paragraphs `<p>` with line breaks `<br>`. That seems to be the best solution since this is the easiest one. You can close the issue if you want to, since the system behaves like expected.
