### ISSUE TITLE
Deep linking to headers

### ISSUE THREAD

**Issue by evert** [michelf/php-markdown#195]
If I missed this feature or feature request somewhere, let me know.

I'm using php-markdown for writing technical documentation, using sculpin. One major thing I'm missing is the ability to deep-link to a h2 or h3 header in any page.

Is this possible to add this to php-markdown, or how can I go about this?

**Comment by michelf** [comment]
If you're using the MarkdownExtra parser, then you can set `id` attributes on your headers: https://michelf.ca/projects/php-markdown/extra/#spe-attr

**Comment by evert** [comment]
Would it at all be interesting to you to also support automatically creating these?

This doesn't break the markdown rules (afaik) and would it make consistent with (some) other implementations.

**Comment by evert** [comment]
BTW... This is a patch that I can write. I just need to know if it's worth my time :)

**Comment by michelf** [comment]
It's unfortunately impossible to be consistent given with existing implementations that do this, as they have chosen to do it in incompatible ways: 

```
## Some header
```

will give you either `some-header` or `someheader` or `some_header` as the `id` to link to. If you have accented letters or non-latin characters things get worse.

My opinion is that generating an id should not be the default behaviour. That said, I would welcome a patch against the `MarkdownExtra` class allowing a user-defined function to be defined through a configuration parameter named `header_id_func`. See `url_filter_func` for an example.

**Comment by evert** [comment]
Alright, great. @simensen says that he would accept a patch for sculpin supporting that option, if it were available in MarkdownExtra, so I'll be sending you a patch hopefully today!
