### ISSUE TITLE
php parse '<a name="xx"/>' display  is not good

### ISSUE THREAD

**Issue by lhkzh** [michelf/php-markdown#203]
## like this md
- [php](#php)
- [js](#js)

<a name="php"/>
# PHP

<pre>
php_code_info
</pre>

<a name="js"/>
# js

<pre>
js_code_info
</pre>

**Comment by pce** [comment]
if you disable javascript on github, the links doesn't work anymore, because there is no direct named link (prefixed with `user-content-`) in the markup of this document, this feature is implemented in javascript. 

```
        <p>##like this md##</p>

<ul>
<li><a href="#php">php</a></li>
<li><a href="#js">js</a></li>
</ul>

<p><a name="user-content-php"></a></p><a name="user-content-php">

<h1>PHP</h1>

<pre>php_code_info
</pre>

</a><p><a name="user-content-php"></a><a name="user-content-js"></a></p><a name="user-content-js">

<h1>js</h1>

<pre>js_code_info
</pre></a>
```

**Comment by michelf** [comment]
@lhkzh: I'll just point out that tags ending with `/>` is an XML feature that is ignored by HTML parsers. It's better to use `<a name="xx"></a>` to properly close the element in the eye of an HTML parser.
