### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by SignpostMarv** [michelf/php-markdown#21]
I'm thinking it'd be handy for those of us that tweak/refactor the parser to be able to have a set of automated tests to ensure parsing hasn't been broken.

Not entirely sure what the setup for that would be, but I'd imagine it'd involve a directory of markdown files that get parsed with the test script to indicate the degree of correctness that a parser provides compared to the expected html output ?

**Comment by michelf** [comment]
This already exists as an external, non-Github project. I guess I should put it on Github.
http://git.michelf.com/mdtest/

**Comment by SignpostMarv** [comment]
github goodness would be good :D

**Comment by michelf** [comment]
Forgot to close this issue after making the test suite available on Github. Here you go: https://github.com/michelf/mdtest
