### ISSUE TITLE
Returns empty string, doHeaders at fault?

### ISSUE THREAD

**Issue by wesbaker** [michelf/php-markdown#213]
We're having an odd issue where the parser is returning an empty string. Digging deeper, it looks like the first `preg_replace_callback()` is at fault in `doHeaders()`. Here's an example string that'll cause issues:

> {} {abcdefghijklmnopqr:abcdefgh}

If you take a look at `$text` within `doHeaders()` it's what you'd expect before the `preg_replace_callback()` and `NULL` afterwards.

**Comment by michelf** [comment]
I'm going to suggest something for you to try. Replace the `(?:` in the regular expression with a `(?>` at lines 134 and 136 of the MarkdownExtra.php file. I suspect this is causing unnecessary backtracking, and when it's too much `preg_replace_callback` aborts.

**Comment by wesbaker** [comment]
That seems to fix it for me. Want me to run any other tests? Also, huge apology for not responding sooner.
