### ISSUE TITLE
Parsing problems when using 'and' in headlines

### ISSUE THREAD

**Issue by itsjavi** [michelf/php-markdown#216]
Hello, I am obtaining an empty string in `MarkdownExtra::defaultTransform` when using an `and` in the headline. Here is the problematic line:

`### Classes, interfaces and traits {#classes-interfaces-and-traits}`

Then the rest of the markdown is not parsed, and I am getting an empty string. No clue of what's happening because the parser does not throw any exception or warning.

When I change it to 

`### Classes, interfaces & traits {#classes-interfaces-traits}`

It works...

**Comment by michelf** [comment]
There is a similar problem and a proposed fix in #213. Please let me know if it works.
