### ISSUE TITLE
Change image size?

### ISSUE THREAD

**Issue by zazzaz** [michelf/php-markdown#217]
Hi there, I just got started with PHP markdown. I love it but there is one thing bugging me: 
how can I change the size of an image using php-markdown. Cause some of the uploaded images are quite big.

As far as I know, in some markdown softwares, I cloud append =WIDTHxHEIGHT after the URL

like ![](./pic/pic1_50.png =100x20) 

Is there any similar function in php-markdown?

Thanks.

**Comment by michelf** [comment]
No, this is not supported. You can use HTML though:

```
<img src="./pic/pic1_50.png" width="100" height="20">
```

**Comment by zazzaz** [comment]
Thanks any way. :100:
