### ISSUE TITLE
php-markdown作为扩展插件加入MediaWiki后，页面的P标签直接显示了

### ISSUE THREAD

**Issue by leopardoooo** [michelf/php-markdown#219]
Hello，伟大的作者：

  当我按照mediawiki官方的[Extension:MarkdownSyntax](https://www.mediawiki.org/wiki/Extension:MarkdownSyntax) 加入php-markdown之后，我页面上的一些内容有些变化了，比如被直接显示成了&lt; p>标题&lt;/p>在浏览器的Tab页上，还有很多按钮之类的都自动加上了&lt;p>标签。不知道您是否遇到过这种情况？我该怎么处理？

![image](https://cloud.githubusercontent.com/assets/4019562/12004871/138850a4-abb9-11e5-92bf-f18f54772eaf.png)

![image](https://cloud.githubusercontent.com/assets/4019562/12004872/28f60d96-abb9-11e5-9441-b383b935bb41.png)

![image](https://cloud.githubusercontent.com/assets/4019562/12004874/690cb70e-abb9-11e5-82c6-514ca0bf5399.png)

**Comment by michelf** [comment]
Sorry, I don't understand this language. If the is about the MediaWiki Markdown extension, it wasn't created by me. You should contact the author of that extension.

If you think the bug is within PHP Markdown, I need the text input and text output you get from calling the `transform` or `defaultTransform` function in order to investigate.

**Comment by Reconix** [comment]
Translation I Believe says {
Hello, great authors:

When I follow the official mediawiki Extension: MarkdownSyntax After joining php-markdown, some of the content on my page some changes, such as being displayed directly became <p> Title </ p> Tab on the browser page, there are many buttons and the like are automatically added the <p> tag. I do not know whether you encountered such a situation? How can I deal with? }

**Comment by michelf** [comment]
Thanks @Reconix for the translation.

The `<p>` shouldn't be there in the output. My guess is that the list item is separated by a blank line from the next one in the input, causing PHP Markdown to wrap its content in a paragraph in the output, and then the MediaWiki extension probably mishandle the paragraph by making the `<p>` show up. Perhaps removing a blank line in the input would fix the page.

**Comment by shuimuyian** [comment]
语言差异啊
