### ISSUE TITLE
Tables extra alignment broken by css resets

### ISSUE THREAD

**Issue by jbroadway** [michelf/php-markdown#22]
Since `td{text-align:left;}` is a common CSS reset, which breaks `align="right"` style alignment, php-markdown should change those to `style="text-align:right"` in the output.

I would supply a pull request, but I don't see the extras in the github repo (and couldn't find a separate repo for them).

**Comment by michelf** [comment]
There is no separate repo for Extra, it's a separate branch.

As for the generated markup, I think it's safer to keep it as it is, for now at least. You can style it adequately with `td[align="right"] { text-align:right }`, and changing the markup would break existing style sheet with similar rules.

But more generally, I think we need a path forward for the generated markup. This prompted me to create a [planning page](https://github.com/michelf/php-markdown/wiki/HTML5-update) on the wiki (which I just activated).

**Comment by jbroadway** [comment]
That sounds like the best approach for compatibility while moving forward at the same time. Will keep an eye on the planning page and contribute what I can. Thanks!

**Comment by michelf** [comment]
See issue #58 for discussing about the output.
