### ISSUE TITLE
Customizable Footnote ID and Classes

### ISSUE THREAD

**Issue by taufik-nurrohman** [michelf/php-markdown#220]
It would be nice to have full access to make custom footnote ID and classes, which will remove `fn_id_prefix` option, &hellip; replaced by `fn_link_id` and `fn_backlink_id` instead:

``` .php
public $fn_link_id = 'fn:%s';
public $fn_backlink_id = 'fnref:%s';
```

And for classes:

``` .php
public $fn_class = 'footnotes';
public $fn_link_class = 'footnote-ref';
public $fn_backlink_class = 'footnote-backref';
```

**Comment by michelf** [comment]
Hum, and what is the reason you are asking for this?

**Comment by taufik-nurrohman** [comment]
Compatibility with the old posts I think, that was not built with **Markdown**, but already has manual footnotes with quirks that does not conform to standard **Markdown**. By enabling this feature, users who already have much blog posts with their own footnotes writing styles can switch using **Markdown** without having to change the manual footnotes format on their old posts to conform to standard **Markdown**.

What users need to do is to change the **Markdown** footnote pattern to follow the footnote format on the old posts they have made with certain standards.

Lets say, _Wikipedia_ uses `cite_note-%d` and `cite_ref-%d` in their footnotes.

**Comment by michelf** [comment]
When you say "I think", is there some user somewhere asking for this, or is just that some users could in theory want that?

What you suggested above actually isn't enough to describe the backlink reference in the presence of multiple footnotes. I'd lean towards offering a way to set a callback function if you need custom ids for this. But I'm still sceptical about the use case.

**Comment by taufik-nurrohman** [comment]
&ldquo;could in theory want that&rdquo; and because using `preg_replace` and such to make custom markup are hacky.

OK then, thanks for answering btw.
