### ISSUE TITLE
Parsing Markdown with emoji shorthand

### ISSUE THREAD

**Issue by euclid1990** [michelf/php-markdown#224]
I have some shorthand to display emoji:
Example: `:_smile_:, :kissing_closed_eyes:, :smile_cat:, ...`
Each shorthand reference to an image like 

```
<img class="emoji" title=":_smile_:" alt=":_smile_:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png" height="20" width="20" align="absmiddle">
```

Please help me:
How to display the shorthand when render a Text by PHP Markdown ? Because when I render markdown with shorthand (have underline), its become a italic text :(
Example:

```
use \Michelf\MarkdownExtra;
$my_text = "### My emoji icons   :smile_cat:     :_smile_:";
$my_html = MarkdownExtra::defaultTransform($my_text);
```

It ouput:
`"<h3>My emoji icons   :smile_cat:     :<em>smile</em>:</h3>\n"` => I have no rule to replace shorthand with img html tag.

Thank you ! :smile:

**Comment by michelf** [comment]
That's not supported.

But you could create your own subclass of the parser and add a new transformation to the the span gamut that does what you want. 🍀

**Comment by euclid1990** [comment]
@michelf Thank you, hope it will be support in the next version :sob:

**Comment by euclid1990** [comment]
@michelf I have an other question. How to bind target="_blank" to link in Mardown
Example:

```
[I'm an inline-style link](https://www.google.com)
```

I want it render to:

```
<a href="https://www.google.com" target="_blank">I'm an inline-style link</a>
```

Instead of

```
<a href="https://www.google.com">I'm an inline-style link</a>
```

Thank you :+1:

**Comment by ghost** [comment]
Hi @euclid1990, 
You probably got the answer since long time ago but if someone else is still looking at, here is the way to achieve that: 
`[I'm an inline-style link](https://www.google.com){target=_blank}`

**Comment by jerry1970** [comment]
I am working on an extension that has a list of domain names that are considered internal, other links are external. All internal links will have the domain name removed, all other links get the target=blank attribute.
