### ISSUE TITLE
How to highlight programing language with file name

### ISSUE THREAD

**Issue by euclid1990** [michelf/php-markdown#225]
I try the following Markdown code:

> ``` javascript:main.js
> function main() {
>   return 1;
> }
> ```

But it not highlight with below html:

```
<pre>
    <code class="javascript:main.js">function main() {
        return 1;
    }</code>
</pre>
```

Please help me !

Note: main.js is file name !

I found the way to show above html, but it not formal: It is add **\.** into regex of PHP MarkdownExtra
![selection_064](https://cloud.githubusercontent.com/assets/5584709/12949026/5577d9d2-d038-11e5-804c-49a6b6153de9.png)

@michelf : Could you support it in next version ?

**Comment by michelf** [comment]
There is no direct code highlighting support in PHP Markdown. What you can do is configure the parser to use an external library to do code highlighting using the `code_block_content_func` callback. Alternatively you can use a javascript code highlighter that will work on the client side.
