### ISSUE TITLE
PHP Markdown Extra parses markdown inside <style> tags

### ISSUE THREAD

**Issue by benlk** [michelf/php-markdown#227]
I'm writing some `<style>` tags inside my parsed Markdown, to style HTML elements used in a demonstration. The idea is that the styles inside the `<style>` element would affect some other HTML elements placed in the Markdown file, and I'd naturally want to select those elements by their `id`s.

However, PHP Markdown Extra is parsing lines beginning with `#` as headers, and four-space indents in the CSS inside the `<style>` as Markdown code blocks. Additionally, the `<style></style>` is wrapped in `p` tags.

Example input:

``` md
Markdown paragraph.

<style type="text/css">
.showy-hidey {
    display: none; 
}
#check-me:checked + .showy-hidey {
    display: inline;
    color: orange;
}
</style>

Some custom HTML.
```

Expected output:

``` html
<p>Markdown paragraph.</p>

<style type="text/css">
.showy-hidey {
    display: none; 
}
#check-me:checked + .showy-hidey {
    display: inline;
    color: orange;
}
</style>

<p>Some custom HTML.</p>
```

Actual output:

``` html
<p>Markdown paragraph.</p>

<p><style type="text/css">
.showy-hidey {
    display: none; 
}</p>

<h1>check-me:checked + .showy-hidey {</h1>

<pre><code>display: inline;
color: orange;
</code></pre>

<p>}
</style></p>

<p>Some custom HTML.</p>
```

**Comment by michelf** [comment]
I can't reproduce this on the [dingus](https://michelf.ca/projects/php-markdown/dingus/): it produces the expected output. Are you sure you tested the same example you posted?
