### ISSUE TITLE
No Formatting When Markdown Plugin Is Disabled

### ISSUE THREAD

**Issue by ghost** [michelf/php-markdown#23]
I do understand that this is not a bug, but I would like to ask anyway. Markdown and Markdown Extra are awesome at what they promise to do, but there are 2 problems:
- You may not develop and support the plugin forever.
- If the users of your plugin plan to make a switch to HTML, their old posts show raw unformatted Markdown posts.
- Correct me if I am wrong, but the plugin does on the fly conversion of Markdown to HTML, right? This could be another negative as the server should process it on every page load.

There is [at least one Wordpress plugin](http://wordpress.org/extend/plugins/markdown-on-save/) that automatically converts posts to HTML upon 'publishing' and reverse-converts back to Markdown when 'editing'.

Do you have any plans on implementing something similar? I just wanted to know.

Have no negative intention with regards to the plugin. If you find this as useless, just consider it as my feedback. :) And thanks for the wonderful open source stuff.

**Comment by michelf** [comment]
I don't plan to do anything about it, sorry.

Converting back to Markdown on editing only half work: you can't get back the original Markdown text when converting back to Markdown, you'll simply get another Markdown representation of the same text, which in most cases is not the same as what you wrote. The original Markdown text has to be stored separately, but this is rather difficult with Wordpress.

You're right, it does on-the-fly conversion, which is suboptimal. But the problem runs deeper than that: mostly all of Wordpress text filers work like that (smilies, texturize, auto_p). In my humble opinion, the way Wordpress process its text input is [contorted, hard to work with, and somewhat dysfunctional](http://michelf.com/weblog/2005/wordpress-text-flow-vs-markdown/). I'm not going to write a plugin to fix Wordpress flaws. If on-the-fly conversion concerns you, there is at least one cache plugin out there.

I'll leave this issue open, in case someone else finds it and wants to work on this. I recognize it's a legitimate issue and I might be willing to accept patches.

**Comment by michelf** [comment]
Just checked your link. It does not convert HTML back to Markdown, it saves the formatted text separately. Perhaps things have improved since I last worked on Wordpress integration with PHP Markdown. This is somewhat encouraging. I don't really have the time to work on that right now though.

**Comment by ghost** [comment]
@michelf : That's what I actually tried to say, but didn't put it properly in words. Anyway, I hope caching will relieve the server of some processing load. Thanks for the tip.
