### ISSUE TITLE
Do markdown tables work at all?

### ISSUE THREAD

**Issue by edrush** [michelf/php-markdown#234]
Hi,

I do not find a way to make md tables turn to html, not even those examples [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Is it possible at all or only "allowed html"?

**Comment by michelf** [comment]
Are you using `Markdown` or `MarkdownExtra`? Tables are not part of the [base Markdown syntax], so so you need to use `MarkdownExtra` parser.

**Comment by edrush** [comment]
Hi, thank you, I did try that, without change, no html table. Is there anything else I have to think of?

Am 17.06.16 um 12:30 schrieb Michel Fortin:

**Comment by edrush** [comment]
I'm sorry, your explanation of MarkdownExtra and my syntax fix in the markdown that I just discovered solved it...thanks for your answer!
