### ISSUE TITLE
Version 1.0.1 not working with PHP 7

### ISSUE THREAD

**Issue by codebig** [michelf/php-markdown#235]
We are using markdown Version 1.0.1 in our project. Evereything was working fine until yesterday when we upgraded our PHP to PHP7. Suddenly we are seeing the exception 
<code>ErrorException [ Deprecated ]: Methods with the same name as their class will not be constructors in a future version of PHP; Markdown_Parser has a deprecated constructor
APPPATH\vendor\markdown\markdown.php [ 191 ]
186 
187 #
188 # Markdown Parser Class
189 #
190 
191 class Markdown_Parser {
</code>

Any ideas?

**Comment by jackmcdade** [comment]
Maybe upgrade to the latest version?

**Comment by michelf** [comment]
If you want to stay with 1.0.1, you edit the code and change `function Markdown_Parser` to `function __construct`. Or you can upgrade to the latest version of PHP Markdown Lib.
