### ISSUE TITLE
> (greater than) character not escaped?

### ISSUE THREAD

**Issue by JustinLardinois** [michelf/php-markdown#236]
The parser escapes `&` and `<` characters but not `>` in the `encodeAmpsAndAngles` function. Is there a reason for this? It seems inconsistent.

**Comment by michelf** [comment]
Because there is no need to.

**Comment by JustinLardinois** [comment]
What do you mean? These characters are required to be escaped in HTML documents.

**Comment by ljacqu** [comment]
No, `>` is not required to be escaped. Only `<` and `&` are, though it doesn't hurt to escape `>` as well.
