### ISSUE TITLE
How to support fenced code blocks with four space start?

### ISSUE THREAD

**Issue by shishirui** [michelf/php-markdown#238]
Many markdown editor consider the text started with four space is the fenced code blocks. For example:

```
    This is code.
    This is code.
```

But not this:

```
\~~~
This is code.
This is code.
\~~~
```

I noticed that the php-markdown lib does not converts text started with four space to fenced code blocks. Could you please tell me how to support this?

**Comment by michelf** [comment]
I'm not too sure about sure what you are asking, but hopefully the following will answer the question. There are two kinds of code blocks, the indented kind (4-space indent creates a code block) and the fenced kind (````` or `~~~` creates a fence delimiting the code block). The fenced kind is only supported with the `MarkdownExtra` parser since it is an extension to the original Markdown syntax.

In both cases you can indent the content by adding spaces at the start of the lines.

Feel free to experiment on the [PHP Markdown Dingus](https://michelf.ca/projects/php-markdown/dingus/). If something doesn't seem right, please send me an example with the **input**, the **output you got** and the **output you expected**.

**Comment by shishirui** [comment]
After some test on the PHP Markdown Dingus and my codes. I found that it's my mistake. At first I thought, the indented kind of code blocks is unsupported in php-markdown. But then I found I was wrong, very sorry.
