### ISSUE TITLE
Placing image between `figure`tag does not work

### ISSUE THREAD

**Issue by ghost** [michelf/php-markdown#239]
PHP Markdown Lib 1.6.0
## This work

```
![My picture][img_01]
[img_01]:  http://www.w3.org/html/logo/img/mark-word-icon.png "HTML5 for everyone"

```
### Result

```
<p><img src="http://www.w3.org/html/logo/img/mark-word-icon.png" alt="My picture" title="HTML5 for everyone" /></p>
```

![My picture](http://www.w3.org/html/logo/img/mark-word-icon.png)
## This does not work

Image is not displayed but markdown code.

```
<figure>
![My picture][img_01]
</figure>

[img_01]:  http://www.w3.org/html/logo/img/mark-word-icon.png "HTML5 for everyone"
```
### Result

```
<figure>
![My picture][img_01]
</figure>
```
## This work but unwanted 'p' tag is added

Adding attribute `markdown="block"`to `figure`tag make it work but code is then wrapped in unwanted `p`tag.

```
<figure  markdown="block">
![My picture][img_01]
</figure>
[img_01]:  http://www.w3.org/html/logo/img/mark-word-icon.png "HTML5 for everyone"
```
### Result

```
<figure>

<p><img src="http://www.w3.org/html/logo/img/mark-word-icon.png" alt="My picture" title="HTML5 for everyone" /></p>

</figure>
```

**Comment by michelf** [comment]
You can use `markdown="span"` to get rid of the unwanted `<p>`. Perhaps span-mode should be the default when using `markdown="1"` on `<figure>`; I'll have to think about it.

**Comment by ghost** [comment]
Ok, thank you!

**Comment by ghost** [comment]
Ok, thank you!
But what does an image inside `<figure>`doesn't work? Is this a desired behavior?

On previous version of `markdown.php` this worked like a charm without any attributes (markdown: and markdownExtra:1.2.7). So to avoid modifying already existing pages maybe span-mode should be the default setting.

**Comment by michelf** [comment]
`<figure>` is a block-level element, like `<div>`, `<p>` and `<blockquote>`. The Markdown rule for block-level elements is to not treat their content as Markdown-formatted.

```
<figure>
    <img alt="My picture" src="http://www.w3.org/html/logo/img/mark-word-icon.png" title="HTML5 for everyone">
</figure>
```

**Comment by ghost** [comment]
Ok, thank you.

So in order to use PHP Markdown Lib 1.6.0 wether existing content must be modified by adding `markdown="span"` attribute to `figure` tag or  markdown syntax must not be placed inside `figure` tag.

Furthermore it seems `figure` is not quite a _block-level_ element as all elements new in HTML5: [Block-level elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements).

**Comment by michelf** [comment]
In general, HTML 5 uses the term "flow content" instead of block-level. That doesn't change things much as far as Markdown is concerned. You can't put a `<figure>` inside of a `<p>`, so it must be treated as block-level form the perspective of Markdown.

**Comment by ghost** [comment]
Ok. Thank you for all these explanations.
