### ISSUE TITLE
How to replace $x<y$ with $x < y$

### ISSUE THREAD

**Issue by fardina** [michelf/php-markdown#240]
I am using php markdown in my website for writing mathematics.
If I use less than sign it causes some problems in rendering mathjax, see here: http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents

How can I search all the text for less than sign like "x<y" and replace it by "x < y"?

Thank you for your help.

**Comment by michelf** [comment]
Is this a general question about how to replace text in PHP? There's the `str_replace` function, or `preg_replace` if you need regular expressions.

**Comment by Gummibeer** [comment]
@fardina wouldn't encoding the html special chars also work?

> Alternatively, you can use the HTML entities &lt;, &gt; and &amp; to encode these characters so that the browser will not interpret them, but MathJax will. E.g.,
> `... when $x &lt; y$ we have ...`

http://php.net/manual/de/function.htmlspecialchars.php
