### ISSUE TITLE
Please add more tags (for each release)

### ISSUE THREAD

**Issue by Quix0r** [michelf/php-markdown#250]
Hello,

I'm currently hacking on Friendica ( see https://github.com/friendica/friendica ) where I try to maintain used external libraries (as git sub modules). Most libraries provide some release tags, like "x.y.z", but sadly your lib only has "lib" (updated enough) which seems to be the development branch.

Could you please create tags on each release so it is safer and easier for me to update to the right version?

Sorry for some rudeness (if applyable), non-native English speaker here. :-)

**Comment by michelf** [comment]
Well, I do make a tag for each "release", in other words every time I increment the version number. Only, I don't have much time to devote to PHP Markdown so I often postpone releases until later. It's a bit unfortunate really, but the release process involves updating the documentation on the website as well as a few other things and it's a bit time consuming, so I tend to wait until a number of worthwhile fixes/improvements have accumulated before making a release.

I'm not sure what the solution is really.

I'll try to make a release today or tomorrow, as it's a bit overdue.

_(non-native speaker here too, and no rudeness detected)_
