### ISSUE TITLE
no parsing inside HTML tags

### ISSUE THREAD

**Issue by 1manfactory** [michelf/php-markdown#251]
Hello, I am not sure how to handle this. I kindly ask for your help.

When parsing this

`<p class="center">*Hello*</p>`

I would expect this as result:

`<p class="center"><em>Hello</em</p>`

Instead I (still) get this:

`<p class="center">*Hello*</p>`

How can I achieve parsing inside html code?

**Comment by michelf** [comment]
1. make sure you are using the Markdown Extra parser.
2. Add `markdown="1"` to your paragraph tag.

**Comment by 1manfactory** [comment]
You are my hero!
Thank you so much.
