### ISSUE TITLE
Two spaces at line end not always recognized

### ISSUE THREAD

**Issue by 1manfactory** [michelf/php-markdown#252]
I am using MarkdownExtra

When parsing this (first two lines with spaces at the end):

```
line 1  
line 2  
line 3
```

I get this (as it should):

```
<p>line 1<br />
line 2<br />
line 3</p>
```

But when parsing this (also with spaces at the end)

```
<p markdown="1" class="poem">  
line 1  
line 2  
line 3
</p>
```

I get this

```
<p class="poem">  
line 1  
line 2  
line 3
</p>
```

So it looks to as the spaces are not recognized here. Or am I missing a notch somewhere?

**Comment by michelf** [comment]
Looks like a bug.

I observe that works correctly with `<div markdown="1">`, but not with `p`.

**Comment by 1manfactory** [comment]
Shall I wait for a fix or build a work around myself?

**Comment by michelf** [comment]
I'll try to check it out this weekend.
