### ISSUE TITLE
Better Test Suite

### ISSUE THREAD

**Issue by michelf** [michelf/php-markdown#256]
Currently, I use [MDTest](https://github.com/michelf/mdtest) to test PHP Markdown after each change. It's done manually with two commands:

    ./mdtest.php -f \\Michelf\\Markdown::defaultTransform -t "Markdown" -t "PHP Markdown"
    ./mdtest.php -f \\Michelf\\MarkdownExtra::defaultTransform -t "Markdown" -t "PHP Markdown" -t "PHP Markdown Extra"

The first line runs the Markdown and PHP Markdown test suites against the `Markdown` parser, while the seconds tests the same test suites, plus the PHP Markdown Extra suite, against the `MarkdownExtra` parser. (Note that php-markdown is a submodule inside MDTest, that's why it can find the parser classes.)

The output of MDTest tells me whether there was any error, comparing a normalized form of the output with the expected output. It can display a diff on-demand between the output and what was expected (with `-d`). It displays the time it takes to run each tests... which is ridiculously small these days because our CPUs are so fast, but is still useful to asses there is no significant performance regression. I also have a private test suite that includes some lengthy text files that works better to test speed regression that I generally add to the command above, but unfortunately those documents are not public.

I run MDTest as a validation step before pushing anything to the repository. Everything should pass, with one exception: the test for emphasis in the PHP Markdown test suite is incompatible with `MarkdownExtra` and the expectation is that it fails when testing `MarkdownExtra` (I know, it's clumsy). Then I assess that the speed is not abnormally slow. Once everything is good, I push to Github.

Now, this setup works well for me. But I think it's a put-off for contributions. There's also a few things that currently go untested and that could be improved: basically any non-default configuration of the parser. I wish I had a solution for this, but testing everything here quickly becomes a combinatory explosion.

So I'm open to suggestions. If you have a question about why something is done in a certain way, please ask. I don't have much time to put for improvements here, so most likely if there are changes to be made the implementation will have to be made by someone else.

*Some background on MDTest: the way it works is relic of a time I hoped to make a test suite that other implementations could use. If widely used, it could have helped reduce the fragmentation of Markdown in various parser-dependent syntaxes each with different quirks. That's why it's a command line tool capable of testing can test pretty much any other command line tool that emits some Markdown output. But I'm not sure there's much value in this setup anymore.*

**Comment by michaelbutler** [comment]
OK, I will add to my ToDo list to explore the possibilities here. Thanks!

**Comment by michaelbutler** [comment]
Could be closed, yeah?

**Comment by michelf** [comment]
Indeed. Closing.
