### ISSUE TITLE
Is there an official organization of markdown standard?

### ISSUE THREAD

**Issue by mytharcher** [michelf/php-markdown#27]
I asked this question on stackoverflow.com, but no answer. So I ask here again for more discussion:

http://stackoverflow.com/questions/9222990/is-there-an-official-organization-for-discussing-or-releasing-standard-markdown

**Comment by michelf** [comment]
No organization. There's a [mailing list](http://daringfireball.net/projects/markdown/#discussion-list) frequented by most Markdown implementers and hosted by John Gruber, that's probably the best you can get. But the (plain) Markdown syntax is mostly frozen for a variety of reasons, one of them being that John Gruber has stopped working on it.

**Comment by karlcow** [comment]
A [community group](http://www.w3.org/community/markdown/) has been created at W3C to create a specification for MArkdown.

**Comment by pablox-cl** [comment]
I should add that the group was created in response to Jeff Atwood blog post about the [future of markdown](http://www.codinghorror.com/blog/2012/10/the-future-of-markdown.html).
