### ISSUE TITLE
Some tags don't work

### ISSUE THREAD

**Issue by gabyfle** [michelf/php-markdown#274]
Hey ! I'm using MarkDown Extra but some tags aren't working :/

Here, the list of tags who don't work ( for me ) : 

- Lists ( * & 1. )

- hr ( --- )

- img ( !*[exemple]*(http://exemple.com) )

I don't know if I've done a mistake, here my code of the inclusion of MarkDownExtra : 

```PHP
        // Inluding the MarkDown Extra system
	require_once 'include/markdown/MarkdownExtra.inc.php';
		
	use Michelf\MarkdownExtra;
	$parser = new MarkDownExtra;
```

Thanks in advance for your help,

Gaby

**Comment by michelf** [comment]
Are you using parser to transform the input? Like this:

    $output = $parser->transform($input);

(This is assuming the Markdown text is in the variable `$input` and you want the HTML result in the variable `$output`.)

**Comment by gabyfle** [comment]
Yes, some tags are working like *italic* or **bold**

**Comment by michelf** [comment]
That's a bit peculiar. It should work. Do you have an example of input text that does not work?

**Comment by gabyfle** [comment]
Yes, so in my database, I've text like that stored : 


```
- Lorem Ipsum dolor sit amet
![Lorem](src/img/img.png){.img-responsive}




##### Lorem Ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. **Cras** ac sagittis erat, vitae dignissim nunc. Phasellus congue finibus est in tincidunt. *Quisque* mattis placerat augue non eleifend. Suspendisse ut urna nulla. Donec ligula dui, **aliquet** nec sodales eget, consequat ac mauris. Vestibulum a dolor et sapien vulputate fringilla vitae id purus. Phasellus sed molestie neque, sed vehicula metus. In et odio a risus commodo accumsan. 

- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

And to get the HTML input, I've done that : 

```PHP
$text = nl2br($contents_loop['content']); // To get <br /> instead of \n of the textareas
$text_markdown = $parser->transform($text); // I transform the text right here
```

The ##### are still working, ** and * too but the lists and img arn't working :/

EDIT : 

Maybe I have to parse before convert the \n ?

EDIT² : 

Yes, it was that. When I do the nl2br before parsing, some tags aren't working :)
Compability problems ?

Thanks a lot for your amazing work !

Gaby

**Comment by michelf** [comment]
With `nl2br` you'll get a `<br />` at the end of each line. At that point there is no longer any blank lines and any syntax that depends on a blank line will not work.

You should probably just use `$parser->hard_wrap = true;` if you want all line breaks to become a `<br />`.

**Comment by gabyfle** [comment]
Thanks you a lot for your help, and thanks too for your amazing work !

Gaby
