### ISSUE TITLE
generic discussion: MD syntaxes compatible with (an efficient) HTML back conversion

### ISSUE THREAD

**Issue by Netsaver** [michelf/php-markdown#276]
Hi, 
I want only to share a discussion started at [pandoc](https://groups.google.com/forum/#!topic/pandoc-discuss/LaDpHlLedPo) about the (generic) capability to reverse HTML code to markdown source.
It does not seem a popular matter, anyway I would find useful to allow an efficient _back conversion from HTML to markdown_ (that is to minimize the losses when going forth and back from MD to HTML).
To this end not all source syntaxes and rendering choices are equivalent each other (for instance, in the referred link, the _footnote syntax_ is reported as example; in that case even the '_footnote'_ and _'footnoteref'_ classes in the rendered HTML should be part of the spec, as needed to identify the construct in the back passage...).
The optimum would be _selecting constructs for the markdown extra specification which allow the best degree of reversibility than possible_.   
Well, even if the back conversion has not been (yet) developed, nevertheless when (likely) it will be, it could be too late for selecting a proper syntax to reconstruct the source code, given the increasing standardization (we hope) and the amount of sources spread world wide...
Only to know if you agree with this philosophy.
Thanks and regards,
Netsaver Paul (Rome, IT)

**Comment by michelf** [comment]
The reversibility is not really a goal of Markdown. A bit like you keep the original source code when you compile some code into [bytecode] or [machine code], you should preserve the Markdown source when rendering in HTML so you can make changes later.

[bytecode]: https://en.wikipedia.org/wiki/Bytecode
[machine code]: https://en.wikipedia.org/wiki/Machine_code

There are cases where it is nevertheless useful to convert from HTML to Markdown. If you are in one of those cases, I would suggest [Markdownify](https://github.com/Elephant418/Markdownify).
