### ISSUE TITLE
Link with nested images

### ISSUE THREAD

**Issue by kravets-levko** [michelf/php-markdown#278]
Hi Michel!

Seems that parser does not support markup like this:

```markdown
[![Enlarge](small.jpg)](large.jpg)
```

Expected output:
```html
<a href="large.jpg"> <!-- possibly with target="_blank", but tn necessary -->
  <img src="small.jpg">
</a>
```

Actual output:
```html
[![Enlarge](small.jpg)](large.jpg)
```

For example, GitHub's parser supports such syntax.

**Comment by michelf** [comment]
That's curious. It works on [the dingus](https://michelf.ca/projects/php-markdown/dingus/). Which version are you testing exactly?

**Comment by kravets-levko** [comment]
Michel, I'm terribly sorry. There was an zero-with space (probably copy-pasted :disappointed:). Everything works, I'll close this issue. Sorry for wasting your time.
