### ISSUE TITLE
Remove hashtag comments in PHP files

### ISSUE THREAD

**Issue by rkyoku** [michelf/php-markdown#279]
Hi,

Hashtag comments in PHP files cause bugs:
```PHP message: Fatal error: Comments starting with '#' are deprecated```

We can see some of them in Markdown.php file, e.g.:
```
# Convert all tabs to spaces.
$text = $this->detab($text);
```

Thanks in advance!

**Comment by michelf** [comment]
All I can find in the documentation and more generally on the web is "Comments starting with '#' are now deprecated in .INI files." But this isn’t an .ini file.

Can you tell me which version of PHP causes this error? And, if relevant which configuration options?

**Comment by rkyoku** [comment]
Okay I'll have a look and keep you posted. I have this error in production
only, and had already checked all my ini files prior to checking my PHP
files. Maybe you're right, but that would not help me though :)

Le mer. 12 juil. 2017 12:35, Michel Fortin <notifications@github.com> a
écrit :

**Comment by michelf** [comment]
If the error points to a specific file and line (as it normally does), then it should be obvious whether this is from an .ini file or not.

Also, I'm not that much attached to those '#' comments. They are simply a relic of the past. (PHP Markdown is descended from a Perl script.) If I get a pull request that replaces them with `//` I'll accept it.

**Comment by rkyoku** [comment]
Alas, it doesn't... :( it says "line 1 in Unknown".

I'll investigate it, you're probably right and it is not from Markdown.
I'll keep you posted

Le mer. 12 juil. 2017 12:58, Michel Fortin <notifications@github.com> a
écrit :

**Comment by rkyoku** [comment]
Ok, you were right. The issue was not coming from an INI file (as I did check them all prior to coming here), but from a CONF file... What is strange is that I did not see this error before, and I thought it was because of my fresh composer install.

Sorry for the false positive, I am closing this ticket!

Congrats on the great lib btw :+1: thank you for sharing it!
