### ISSUE TITLE
Don't parse inside

### ISSUE THREAD

**Issue by ArthaTi** [michelf/php-markdown#281]
Sorry if this is wrong place to ask about that.

I'm creating my own language interpreter (called Forum Scripting Engine / FSE) to work with MD. Everything inside `</ />` should be parsed as FSE.

But:

- User input is protected by php `htmlspecialchars` function, so the FSE block isn't `</ />`, but `&lt;/ /&gt;`
- Markdown shouldn't be parsed inside any FSE block.
- FSE block isn't parsed when inside `<code>`
- FSE output should be parsed using Markdown when done.

Let's say I use `parse()` function to parse FSE, so right now the code looks like:

```
MarkdownExtra::defaultTranform();
parse();
```

Everything works right, until any MD reserved character is placed in the block.

How can I get such result? Thanks.

**Comment by michelf** [comment]
I think you need to integrate this with the `hashHTMLBlocks` group of functions. Specifically, make sure your tag type is recognized as a tag by the big `$block_tag_re` regular expression that splits tag tokens from the rest of the text and then add a new `if` like this one [here] to handle your tag.

[here]: https://github.com/michelf/php-markdown/blob/lib/Michelf/MarkdownExtra.php#L551

**Comment by ArthaTi** [comment]
@michelf I've added the tag to the regex, but it didn't worked. I didn't notice the `if`, so I will try. Thanks

**Comment by ArthaTi** [comment]
@michelf, umm... I don't really understand what should I do.

What I understand now is:

- Add new `elseif` to the place you specified.
- The `if`'s condition should be regex matching the FSE block.
- And then? How I can do that MD just leaves that without parsing?

**Comment by michelf** [comment]
The HTML Block parser is mostly just a pre-processing pass before the rest of the Markdown syntax gets parsed.

The `$parsed .= $block_text;` you see in the currently existing `else if` adds text to the text that was parsed by the HTML block parser. But that "parsed" text is only parsed as far as the HTML Block parser is concerned; it remains to be parsed by the rest of Markdown so if you process it your way and the output includes headers, code blocks or other things they'll get parsed like the rest.

**Comment by ArthaTi** [comment]
Ok, I just escaped every single md special character and replaced new-lines by spaces, as my language doesn't need them. It started to work, so i'm closing the issue.
