### ISSUE TITLE
Automated PHPUnit Tests, Code Coverage reports, etc?

### ISSUE THREAD

**Issue by michaelbutler** [michelf/php-markdown#290]
Thoughts on adding a CI system such as Circle-CI or Travis to this github repo? I know you already have a separate repo MDTests for testing this, but I find it odd that it's in a separate repo, this could be done in the same repo and run in automated fashion so you would know immediately on PRs if something broke, or some new code is untested (hasn't been "run through").

**Comment by michelf** [comment]
I agree with all of this. See #256. Help welcome.
