### ISSUE TITLE
XSS Issues

### ISSUE THREAD

**Issue by thehonkinggoose** [michelf/php-markdown#293]
You can run malicious JavaScript by including `[Click Me](javascript:alert(9);)` in a link. This bug can be mitigated with a content security policy by disabling inline JavaScript. The use of `<script>` tags also works :/

**Comment by michelf** [comment]
Indeed. [Markdown is not meant to be a content sanitizer](https://michelf.ca/blog/2010/markdown-and-xss/).

**Comment by michelf** [comment]
That said, you can use `no_markup` it to disallow HTML tags, and `url_filter_func` to implement your own URL filtering policy. See the [configuration options](https://michelf.ca/projects/php-markdown/configuration/). With this, you should be able to make it pretty safe.
