### ISSUE TITLE
Feature request: parse link texts and image titles

### ISSUE THREAD

**Issue by jerry1970** [michelf/php-markdown#301]
I have made an extension that runs the spanGamut on link text and image titles, but I think that would make a nice feature as settings: `$transform_link_text` and `$transform_img_title`.

**Comment by michelf** [comment]
I'm not sure what this is about. Can you give a sample input and its corresponding desired output?

**Comment by jerry1970** [comment]
Ah yes of course, sorry. And now I come up with an example I realize this is outside the scope of MarkdownExtra, since it only works on an extension... But I'll give the example anyway.

This:
```
![alt text](image.jpg "Photo by _Someone_ from [](someone.net)")
```

used to be parsed like this when I tested it:
```
<img src="image.jpg" alt="alt text" title="Photo by _Someone_ from [Someone.net](http://www.someone.net)" />
```

In my extension, and image is wrapped with spans, like this:
```
<span class="image">
  <img src="image.jpg" alt="alt text" />
  <span class="image-caption">Photo by _Someone_ from [Someone.net](http://www.someone.net)</span>
</span>
```

And with the `$transform_img_title` set to true, it results in this:
```
<span class="image">
  <img src="image.jpg" alt="alt text" />
  <span class="image-caption">Photo by <i>Someone</i> from <a href="http://www.someone.net">Someone.net</a></span>
</span>
```

But this only makes sense if the image title is not in the `title` attribute and therefore not in MarkdownExtra.

I'll close this comment. (You should close some comments too, there are a lot that have been answered. :smile: )
