### ISSUE TITLE
Duplicate Header Id's 

### ISSUE THREAD

**Issue by marcus-at-localhost** [michelf/php-markdown#310]
Hi,

is there a way to avoid or workaround duplicate id's?

```md
# H1
## H2

text

## H2

text
```
=>
```html
<h1 id="h1">H1</h1>
<h2 id="h2">H2</h2>
<p>text</p>
<h2 id="h2">H2</h2>
<p>text</p>
```

I'm using a script to generate a TOC and it chokes on duplicate id's.
Adding a random string in `header_id_func`, helps, but then deep linking is not possible.
Any idea? Or is that the only way around?

```php
$this->md = new \Michelf\MarkdownExtra;

$this->md->header_id_func = function ($header) {
	return preg_replace('/[^a-z0-9]/', '-', strtolower($header)) . '-' . uniqid();
};
```

**Comment by michelf** [comment]
What you need is to use a closure, a function that captures an external variable:
``` php
$taken_ids = array();
function ($header) use (&$taken_ids) {
	$id = preg_replace('/[^a-z0-9]/', '-', strtolower($header));
        while (isset($taken_ids[$id])) {
              // change $id in some way
        }
        $taken_ids[$id] = true; // remember for next time
        return $id;
};
```
[→ More on anonymous functions and closures](https://secure.php.net/manual/en/functions.anonymous.php)

**Comment by marcus-at-localhost** [comment]
Thank you so much for the solution and lesson!
