### ISSUE TITLE
Inserted HTML instead of abbreviations in the block code

### ISSUE THREAD

**Issue by sorbing** [michelf/php-markdown#32]
Instead of a string "HTML" - put in a html tag ABBR:
![Screen with bug](http://i.imgur.com/tlkLm.png)

**Comment by michelf** [comment]
I'm not sure what is the problem. What is the Markdown source that produced this, and what did you expect as the output?

**Comment by sorbing** [comment]
Example:

```
<pre><code class="php">
echo "HTML"; // instead of a string "HTML" inserted tags
</code></pre>
*[HTML]: Hyper Text Markup Language
```

**Comment by michelf** [comment]
Now I understand. :-)

Which version of PHP Markdown Extra are you using? I can't reproduce this behaviour on the dingus by copy-pasting your example.
http://michelf.com/projects/php-markdown/dingus/

**Comment by sorbing** [comment]
it is this): https://github.com/coreyworrell/php-markdown/blob/e90b9127ab79f78a4359a87757d5221ffd6c77e5/markdown.php
I needed a support "manual class set" for the code block:

```
~~~ php
// code
~~\~
```

**Comment by michelf** [comment]
Ok, so it looks like it's related to coreyworrell's extension. I'll look at this when I integrate it within the official branch (which should happen in a few weeks). Thanks for the report.

**Comment by michelf** [comment]
@coreyworrell this bug is related to your code. :-)

**Comment by coreyworrell** [comment]
Awesome. @michelf I probably wouldn't merge my fork yet. It seems to be a little buggy, and I haven't taken a look at the code in awhile. I think it'll need a rewrite.

**Comment by michelf** [comment]
commit 6ebb841e7dc2f
