### ISSUE TITLE
Simple mailto:link is broken

### ISSUE THREAD

**Issue by daftmilk** [michelf/php-markdown#320]
```
MarkdownExtra::defaultTransform('<test@example.com>')
```

translates to…

```
<p><a href="&#x6d;&#97;&#x69;&#108;&#x74;&#111;:&#x74;&#101;&#x73;&#116;&#x40;&#101;&#120;&#x61;&#109;&#x70;&#108;e&#x2e;&#99;&#x6f;&#109;">&#x74;&#101;&#x73;&#116;&#x40;&#101;&#120;&#x61;&#109;&#x70;&#108;e&#x2e;&#99;&#x6f;&#109;</a></p>
```

expected result is…

```
<p><a href="mailto:test@example.com">test@example.com</a></p>
```

**Comment by michelf** [comment]
This is actually on purpose. Quoting: https://daringfireball.net/projects/markdown/syntax#autolink

>Automatic links for email addresses work similarly, except that Markdown will also perform a bit of randomized decimal and hex entity-encoding to help obscure your address from address-harvesting spambots. For example, Markdown will turn this:
>
>     <address@example.com>
>
>into something like this:
>
>     <a href="&#x6D;&#x61;i&#x6C;&#x74;&#x6F;:&#x61;&#x64;&#x64;&#x72;&#x65;
>     &#115;&#115;&#64;&#101;&#120;&#x61;&#109;&#x70;&#x6C;e&#x2E;&#99;&#111;
>     &#109;">&#x61;&#x64;&#x64;&#x72;&#x65;&#115;&#115;&#64;&#101;&#120;&#x61;
>     &#109;&#x70;&#x6C;e&#x2E;&#99;&#111;&#109;</a>
>
> which will render in a browser as a clickable link to “address@example.com”.
>
> (This sort of entity-encoding trick will indeed fool many, if not most, address-harvesting bots, but it definitely won’t fool all of them. It’s better than nothing, but an address published in this way will probably eventually start receiving spam.)
