### ISSUE TITLE
PHP 5.3 support broken in 1.9.0

### ISSUE THREAD

**Issue by GrahamCampbell** [michelf/php-markdown#323]

**Comment by GrahamCampbell** [comment]
Will be fixed by https://github.com/michelf/php-markdown/pull/322.

**Comment by michaelbutler** [comment]
I'm genuinely curious who is still using PHP 5.3 **AND** desiring to run composer update. Granted, such a BC-breaking change should have bumped the major version (e.g. 2.0) instead of a minor patch version.
