### ISSUE TITLE
Support for template variables (e.g. Twig)

### ISSUE THREAD

**Issue by LukasRos** [michelf/php-markdown#327]
I had the issue that I had some text with Twig template variables:

`Hello {{user_first_name}}, _welcome_!`

Which got converted into:

`Hello {{user<em>first</em>name}}, <em>welcome</em>!`

Whereas what I needed is this:

`Hello {{user_first_name}}, <em>welcome</em>!`

I solved this by creating a subclass of `Markdown`and override the `parseSpan($str)` function by adding some instructions for Twig to the RegEx:

    ...
				|
							# comment
				|
					{{      .*?      }}		# template variable
				|
					{%      .*?      %}		# template instruction
				|
					<\?.*?\?> | <%.*?%>		# processing instruction
    ...				

Is there a better solution? Or is this something that could be added to the Markdown class itself? If so, I can add the changes there and send a pull request.

**Comment by michelf** [comment]
The `MarkdownExtra` class reimplements this to suppress underscore-based mid-word emphasis, so you could simply use `MarkdownExtra` instead of `Markdown`.

**Comment by LukasRos** [comment]
Thank you! Using `MarkdownExtra` was sufficient to solve my issue so I have removed my customizations again.
