### ISSUE TITLE
Do not insert "Code Block" into list item

### ISSUE THREAD

**Issue by sorbing** [michelf/php-markdown#33]
Can not insert a "code block" into UL LI.

Example:

```
*   Any text
~~~
// code
~~~
```

Code Block is inserted after the item list.

**Comment by michelf** [comment]
The code block needs to be indented, and must be separated by a blank line. That'll work:

```
*   Any text

    ~~~
    // code
    ~~~
```

**Comment by sorbing** [comment]
Sorry. All fine works - in fact I had a problems with indented. Thanks!
