### ISSUE TITLE
Can you create external links?

### ISSUE THREAD

**Issue by skillmatic-co** [michelf/php-markdown#332]
It seems you can do this with Kramdown by adding `{:target="_blank"}` at the end of a link, like this:

`[Example](https://www.example.com){:target="_blank"}`

But this library doesn't seem to be parsing `{:target="_blank"}`, am I doing something wrong?

**Comment by michelf** [comment]
There is no standard for this in Markdown. Some parsers have implemented variations of this, but not all using the same syntax. With PHP Markdown Extra you can use

    [Example](https://www.example.com){target=_blank}

**Comment by skillmatic-co** [comment]
Got it, so instead of:

```
use Michelf\Markdown;
$my_html = Markdown::defaultTransform($output);
```
I can use:

```
use Michelf\MarkdownExtra;
$my_html = MarkdownExtra::defaultTransform($output);
```

And it will parse `[Example](https://www.example.com){target=_blank}` as an external link.

Closing as this answered my question.
