### ISSUE TITLE
Not encoding existing html entities

### ISSUE THREAD

**Issue by sorbing** [michelf/php-markdown#34]
I propose to use the encode HTML  entities without double encoding for code block. What do you say?

```
htmlspecialchars($code_content, ENT_NOQUOTES, 'utf-8', false);
```

**Comment by michelf** [comment]
This would break code blocks. The whole point of code blocks is so you can easily make HTML sample code out of them. If you don't encode things that looks like entities, you'll see something different from what you wrote in the browser.
