### ISSUE TITLE
Extra paragraph marks generated when using details and summary tags

### ISSUE THREAD

**Issue by jeffmcneill** [michelf/php-markdown#348]
Markdown seems to be generating extra `<p></p>` tags when using `<details></details>` and `<summary></summary>` tags. 

This: 
~~~~
<details><summary>
<h2>A Subhead</h2>
</summary>
<p>Some text</p>
</details>
~~~~
Generates: 
~~~~
<details><summary><p></p>
<h2>A Subhead</h2>
<p></p></summary><p></p>
<p>Some text</p>
<p></p></details>
~~~~

**Comment by michelf** [comment]
A simple workaround is to surround all this in a `<div>`:
```
<div>
<details><summary>
<h2>A Subhead</h2>
</summary>
<p>Some text</p>
</details>
</div>
```
This was fixed [back in April](https://github.com/michelf/php-markdown/pull/329), but I have yet to make a release that includes that fix. I'll try to do it soon. You can also try to use the `master` branch meanwhile.

**Comment by jeffmcneill** [comment]
That workaround didn't work for me. I'll look at the master branch.

Sincerely,

Jeff Mcneill
https://jeffmcneill.com


On Mon, Dec 21, 2020, at 1:11 AM, Michel Fortin wrote:
> 

> A simple workaround is to surround all this in a `<div>`:

> `<div>
<details><summary>
<h2>A Subhead</h2>
</summary>
<p>Some text</p>
</details>
</div>
`

**Comment by michelf** [comment]
Oops, I meant the `lib` branch. `master` is actually the older "classic" parser.

**Comment by jeffmcneill** [comment]
Yes, lib branch does not have this problem. Thanks!
