### ISSUE TITLE
Multiple following blockquotes merged

### ISSUE THREAD

**Issue by paxter** [michelf/php-markdown#363]
I'm entering the following markdown:

```
> first quote

> second quote

> third quote
```

All three quotes are merged into one single blockquote. I'm pretty sure the result should be three different blockquotes and not a single one. Or I'm wrong?

**Comment by michelf** [comment]
This is the intended behavior. See:
<https://daringfireball.net/projects/markdown/syntax#blockquote>

**Comment by paxter** [comment]
Can't find any information about auto merging blockquotes with empty lines between following your link.

Why texts like this should be merged?

```
> first quote




> second quote
```

Why should anybody place empty lines between blockquotes if the intend is not to divide them into separate blockquotes?
Does not make any sense for me. I've never seen any markdown implementation with that behavior.

**Comment by paxter** [comment]
Ah, I see. You are right. Didn't read the inline text of the blockquote examples. But it's not a bad idea to provide an option to change that behavior I think.

This is rendered into two blockquotes:

```
> first quote

test

> second quote
```

Following your logic that has to be also one single blockquote?

**Comment by michelf** [comment]
Notice how the two first blockquote examples on that page have the same content and are probably intended to produce the same output even if it's not explicitly said.

The original Markdown implementation by John Gruber, from which PHP Markdown derived, works that way. Long discussions about this can be found on the Markdown mailing list archive.

So, not a bug, but probably a mistake. [John Grubber in 2006](https://marc.info/?l=markdown-discuss&m=136174335910051&w=2):
> Again, not a bug, but a mistake in the syntax design.

For a very long time, PHP Markdown anchored itself to John Gruber's Markdown.pl parser, making sure they produce the same result "bug for bug" so they were interoperable. Markdown.pl is no longer maintained so this policy has been relaxed a bit. I'm not against the idea of starting to "fix" syntax mistakes such as this one, but I think it needs to be done in a backward compatible way. Probably as a new parser mode, or a new parser class.

**Comment by michelf** [comment]
No, it's two blockquotes. Every paragraph in a blockquote need to start with `>`, or multiple `>` for nested blockquotes. If one paragraph has no blockquote marker, then it isn't in a blockquote.

**Comment by paxter** [comment]
Oh ok, it's per paragraph. Thanks for the explanation.

I will going to change that on my local usage of your markdown parser. It's a showstopper for me and I'm pretty sure, an option to change that behavior would help other people too.

**Comment by paxter** [comment]
I will close that issue because it's the origin behavior as you stated correctly. 

If anyone wants to change that, just remove the following line: https://github.com/michelf/php-markdown/blob/9d7fb2c8ae9155081dcbab275ef945e546cf72ba/Michelf/Markdown.php#L1430

Thanks @michelf for your help and the fast replies. :)

This is still the best php markdown parser class of all over the world!
