### ISSUE TITLE
tag or branch for php 5.3 compatible version

### ISSUE THREAD

**Issue by themightychris** [michelf/php-markdown#364]
I have a legacy project depending on php-markdown that I need to pin to the commit 27bfa1902296eaaaaeef7838af4964589805f90a before the version requirement got bumped to 7.4. Can you put a tag or branch on that commit so I have a more friendly ref to target than the raw commit hash?

**Comment by michaelbutler** [comment]
So, maybe something like `1.9.1` that points to https://github.com/michelf/php-markdown/commit/27bfa1902296eaaaaeef7838af4964589805f90a?

Latest tag currently is 1.9.0 which points to a SHA from 2019 so this sounds reasonable.

**Comment by themightychris** [comment]
@michaelbutler yeah 1.9.1 would be great considering that commit still has 1.9 embedded in the content as its version

**Comment by michelf** [comment]
I'll make both a 1.x branch and a 1.9.1 tag (and update the readme and a couple of things for a proper 1.9.1 release).

**Comment by michelf** [comment]
Ok, so branch `lib-1.x` was added, as well as tag `1.9.1`.
