### ISSUE TITLE
Footnote documentation conflicts with behavior

### ISSUE THREAD

**Issue by jmooring** [michelf/php-markdown#372]
See <https://michelf.ca/projects/php-markdown/extra/#footnotes>

> Note that you cannot make two links to the same footnotes: if you try, the second footnote reference will be left as plain text.

But <https://michelf.ca/projects/php-markdown/dingus/> behaves differently (in a good way).

This:

```markdown
a[^1] b[^1]
[^1]:c
```

Produces this:

```html
<p>a<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup> b<sup id="fnref2:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup></p>

<div class="footnotes" role="doc-endnotes">
<hr />
<ol>

<li id="fn:1" role="doc-endnote">
<p>c&#160;<a href="#fnref:1" class="footnote-backref" role="doc-backlink">&#8617;&#xFE0E;</a> <a href="#fnref2:1" class="footnote-backref" role="doc-backlink">&#8617;&#xFE0E;</a></p>
</li>

</ol>
</div>
```

**Comment by michelf** [comment]
Right. That should have been updated in 2013. I just deleted that sentence.

Thank you.
