### ISSUE TITLE
Nested lists are not always nested

### ISSUE THREAD

**Issue by AntoineFr** [michelf/php-markdown#389]
When I have a multi-level list, some levels aren't nested enough. It seams that is only affects odd levels.

**Code**
```php
<?php

require __DIR__ . '/vendor/Michelf/MarkdownInterface.php';
require __DIR__ . '/vendor/Michelf/Markdown.php';
require __DIR__ . '/vendor/Michelf/MarkdownExtra.php';

$text = <<<MARKDOWN
* List level 1
  * List level 2
    * List level 3
      * List level 4
        * List level 5
          * List level 6
MARKDOWN;

$markdown = new Michelf\MarkdownExtra();

echo $markdown->transform($text);
```

**Result**
```html
<ul>
<li>List level 1

<ul>
<li>List level 2</li>
<li>List level 3

<ul>
<li>List level 4</li>
<li>List level 5

<ul>
<li>List level 6</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
```

**Preview**
![image](https://user-images.githubusercontent.com/4655583/219883181-2a2ea6a8-4c7e-4c3b-b8d7-2141fada2018.png)

**Expected result**
* List level 1
  * List level 2
    * List level 3
      * List level 4
        * List level 5
          * List level 6

**Comment by Krinkle** [comment]
I'm having the same issue, through use in <https://github.com/tighten/jigsaw>.

**Comment by michelf** [comment]
The [Markdown syntax](https://daringfireball.net/projects/markdown/syntax#list) says that nested lists need to be indented by 4 spaces or one tab. The way it actually works with this parser (which mimics the original parser's behavior) is that 1 to 4 spaces count as one indent. So your level 3 item need to be indented by 5 to 8 spaces to count as two levels of indentation, and so on.

**Comment by AntoineFr** [comment]
> The [Markdown syntax](https://daringfireball.net/projects/markdown/syntax#list) says that nested lists need to be indented by 4 spaces or one tab. The way it actually works with this parser (which mimics the original parser's behavior) is that 1 to 4 spaces count as one indent. So your level 3 item need to be indented by 5 to 8 spaces to count as two levels of indentation, and so on.

Thank you for your help, it works when using 5 spaces or 2 tabs. I was confused because on GitHub (for example) you can create nested lists with only 2 spaces!
