### ISSUE TITLE
Alignment images through spaces

### ISSUE THREAD

**Issue by sorbing** [michelf/php-markdown#39]
Alignment images with spaces, as in the dokuwiki eg:

```
![ title](http://site.com/image.png) - left
![title ](http://site.com/image.png) - right
![ title ](http://site.com/image.png) - center
```

Or some other syntax..

**Comment by michelf** [comment]
And what would be the HTML output for that?

I'd rather have a way to specify a class so you can hook style rules to it.

**Comment by sorbing** [comment]
Hook it good of course, but align image with style rules does not work - need a wrapper `<P>`.
Example:

```
![ title ](http://site.com/image.png)
translates to:
<p style="text-align: center"><img src="image.png" /></p>
```

**Comment by sorbing** [comment]
Although probably correct indentation set in URL:

```
![title text]( http://site.com/image.png )
```

**Comment by michelf** [comment]
You don't need a wrapper:

```
img {
  display: block;
  margin: auto;
}
```

Beside, the image syntax is for inline images. Having it affect the enclosing paragraph probably isn't a good idea.

**Comment by sorbing** [comment]
Сentered can be so, In any case it would be convenient to align the image use minimal syntax (spaces or any attribute).
Although CSS hooks may also need.
How to align an image to the right , without the wrapper?

**Comment by NetzwergX** [comment]
You can "align" it by floating it to the left and right.

**Comment by sorbing** [comment]
OK, but not practical for each image write `style="display: block; float: right"` - benefits markdown markup fade (disappear).

**Comment by michelf** [comment]
I'm not too trilled by the whole idea shown here. If we add a way to align images, it'll be through a way to add a class attribute that your stylesheet can hook to. This way you're no longer limited by left-, center-, and right-align: you can actually have any presentation you want for your images.

Feel free to reopen an issue for that if you want.

**Comment by sorbing** [comment]
I'm still hoping for an opportunity to align the image with a space character)
How to reopen an issue?

**Comment by michelf** [comment]
I meant open a new issue about adding a class to images.

**Comment by sorbing** [comment]
Can you give an example of the syntax with the addition of the class?

**Comment by michelf** [comment]
It's likely to be done in a similar way than for headers in pull request #38.

**Comment by aleemb** [comment]
I love the idea of using spaces for alignment. Ended up here while Googling a good solution for it and it's the simplest way for non-techies to grok without getting into markup/css.
