### ISSUE TITLE
Markdown - Advanced blockquote only create one blockquoute even with new line without >

### ISSUE THREAD

**Issue by gautamgarp** [michelf/php-markdown#394]
Dear Team according to your document and latest Markdown editor, this given code should be create two distinct Blockquotes but your's one creating single one. check the example below - 

![image](https://github.com/michelf/php-markdown/assets/133984213/dd8c2f33-96ba-41b2-8b7f-24a1d478d991)

giving output in some other Markdown editor like this  - 

<blockquote>
<p class="has-line-data" data-line-start="4" data-line-end="6">The <code>&gt;</code> on the blank lines is required<br>
to create a single blockquote.</p>
<p class="has-line-data" data-line-start="7" data-line-end="10">If you leave out the extra <code>&gt;</code><br>
you will end up with<br>
two distinct blockquotes.</p>
</blockquote>
<blockquote>
<p class="has-line-data" data-line-start="11" data-line-end="12">testing</p>
</blockquote>

But incase of your code in my application, same one is producing like this - 

<blockquote>
<p>&nbsp;The &gt; on the blank lines is required</p>

<p>&nbsp;to create a single blockquote.</p>

<p>&nbsp; </p>

<p>&nbsp;If you leave out the extra &gt;</p>

<p>&nbsp;you will end up with</p>

<p>&nbsp;two distinct blockquotes.</p>

<p>Testing</p>
</blockquote>

Note: - Hoping for ur resolution on this one asap

**Comment by michelf** [comment]
I'm not sure what you mean by "your document". PHP Markdown is based on the original Markdown syntax and Markdown.pl script written by John Gruber, which has this to say about blockquotes:
https://daringfireball.net/projects/markdown/syntax#blockquote

**Comment by gautamgarp** [comment]
Hi,
Michel, I’m talking about this document- https://support.testrail.com/hc/en-us/articles/7770931349780-Editor-formatting-reference#advanced-blockquotes-0-11

Following this reference, I’m using the blockquote but the other latest one have little extra functionality which the users are referring and we have to change the code accordingly. Like after these mentioned line when I press two new line and use another greater than symbol, it should create a new set of blockquote.

**Comment by michelf** [comment]
All I can say is this document is not about PHP Markdown. TestRail is using a different parser. And different Markdown parsers have different rules about this and other things, it can't really be avoided nowadays. If I change this, it will break existing documents for existing users of the library.
