### ISSUE TITLE
last paragraph of a footnote should keep its <\p> otherwise it can mess with the layout

### ISSUE THREAD

**Issue by evanescente-ondine** [michelf/php-markdown#396]
hi,
There's a nonsensical behavior with backreferences in the php-markdown reference: they should be added always as a direct child of the `<li>` tag, but instead, whenever li ends with a p element inside a footnote, it becomes a child of that paragraph. when it's a blockquote or figure, then the backreference (ex: `<a href="#fnref:9" class="footnote-backref" role="doc-backlink">↩︎</a>`) is a direct child of `<li>` as expected.

Blockquotes always come with an end tag, while paragraphs normally don't need one. It's only a problem with paragraphs, which don't require closing, and because links are inline elements. Except we do **not** want links to enter our paragraph randomly, especially if a display:grid is added. That is not ok...
My proposal is to not remove the finishing tag <\p> before the last p in a footnote, whenever there are multiple paragraphs. it would solve that issue.
 
```
[^note]: Monkeys and chimpanzees have been seen hoarding fruits, perhaps intuiting that they risked missing the occasion to come by again to eat more of them.

<li id="fn:9"><p>Monkeys and chimpanzees have been seen hoarding fruits, perhaps intuiting that they risked missing the occasion to come by again to eat more of them.&nbsp;<a href="#fnref:9" class="footnote-backref" role="doc-backlink">↩︎</a></p></li>

-------------
[^note]: Monkeys and chimpanzees have been seen hoarding fruits, perhaps intuiting that they risked missing the occasion to come by again to eat more of them.
	> AAAAA
	
<li id="fn:9"><p>Monkeys and chimpanzees have been seen hoarding fruits, perhaps intuiting that they risked missing the occasion to come by again to eat more of them.</p><blockquote><p>AAAAA</p></blockquote>&nbsp;<a href="#fnref:9" class="footnote-backref" role="doc-backlink">↩︎</a></li>

-----------------
[^note]: Monkeys and chimpanzees have been seen hoarding fruits, perhaps intuiting that they risked missing the occasion to come by again to eat more of them.

	![squirrel_walnuts](/Images/images_article_instincto/squirel_wallnuts_42_gallions.webp)


<li id="fn:9"><p>Monkeys and chimpanzees have been seen hoarding fruits, perhaps intuiting that they risked missing the occasion to come by again to eat more of them.</p><figure class="image"><a href="http://localhost:1313/Images/images_article_instincto/squirel_wallnuts_42_gallions.webp" target="_blank"><img src="http://localhost:1313/Images/images_article_instincto/squirel_wallnuts_42_gallions.webp"></a></figure>&nbsp;<a href="#fnref:9" class="footnote-backref" role="doc-backlink">↩︎</a></li>
```

**Comment by michelf** [comment]
It is intended behavior that the backlink ↩︎ is added to the last paragraph when the footnotes ends with a paragraph. Otherwise you'd see a lot of one-line footnotes followed by a backlink alone on its own line. This is also how it works everywhere, including here on GitHub[^1][^2][^3]. Is this causing issues?

[^1]: A single-paragraph footnote
[^2]: A footnote with a blockquote:

    > quoting something important here

[^3]: A two-paragraph footnote ending with an image:

    ![icon](https://github.com/michelf/php-markdown/assets/298045/9e5ebe2e-cd23-4e90-9e4d-bd90ab5419e0)

**Comment by nnsite** [comment]
I understand, but yet it's causing issue, although I see how rare a case it is.
In this case the paragraph has a display:grid property, dividing the viewport in as many image as I put inside. the link adds itself and it's not pretty. It won't seem like much to you, but I don't appreciate at all when my layout is disturbed by tools.
With the backref:
![image](https://github.com/michelf/php-markdown/assets/33675148/bd475482-21df-40b9-8fa4-cc75dfa2d2d5)
Without it (editing the DOM tree):
![image](https://github.com/michelf/php-markdown/assets/33675148/20ed1fcd-a922-4db5-bcf6-8c85b3e675b5)
```
<p class="center"><span class="image"><span class="figcaption_class"><a href="https://www.washingtonpost.com/nation/2021/09/30/squirrel-truck-fargo-bill-fischer/" rel="noreferrer noopener nofollow external" target="_blank">[A squirrel hid thousands of walnuts under the hood of a man’s truck. It wasn’t the first time](https://www.washingtonpost.com/nation/2021/09/30/squirrel-truck-fargo-bill-fischer/)</a></span>
<a href="https://national-naturalism.org/Images/images_article_instincto/squirel_wallnuts_42_gallions.webp" target="_blank"><img src="https://national-naturalism.org/Images/images_article_instincto/squirel_wallnuts_42_gallions.webp" ></a></span>
<span class="image"><span class="figcaption_class">That fellow, the acorn woodpecker, <a href="https://youtu.be/cZkAP-CQlhA" rel="noreferrer noopener nofollow external" target="_blank">[could also teach us lessons in foresight:](https://youtu.be/cZkAP-CQlhA)</a></span>
<a href="https://national-naturalism.org/Images/images_article_instincto/acorn_woodpeckers.webp" target="_blank"><img src="https://national-naturalism.org/Images/images_article_instincto/acorn_woodpeckers.webp" width="1160" height="682" loading="lazy" alt="acorn_woodpeckers" title="That fellow, the acorn woodpecker, [could also teach us lessons in foresight:](https://youtu.be/cZkAP-CQlhA)" sizes="(max-width: 400px) 100vw, (max-width: 604px) 50vw, 35vw" style="max-width:1160px;max-height:min(682px,500px)"></a></span>
&nbsp;<a href="#fnref:9" class="footnote-backref" role="doc-backlink">[↩︎](https://github.com/michelf/php-markdown/issues/396#fnref:9)</a></p>
```
Also, before the link you add `&nbsp;` as pure text, so I can't get rid out of it completely with pure css ! If at least it was part of the link, I could.

**Comment by michelf** [comment]
This is one elaborate footnote! 😎

If you have control over the markup, an easy fix would be to add an HTML comment on its own line at the end of the footnote, like this:
```
[^1]: <p class="x">Something special in this paragraph</p>
    <!-- spacer -->
```
Or you can put the content in a `<div>`:
```
[^1]: <div><p class="x">Something special in this paragraph</p></div>
```
Either way, the footnote doesn't end with a `</p>` anymore and a separate paragraph is added for the backlink.

Philosophically, I think it's reasonable for PHP Markdown to assume it can insert the backlink at the end of the last paragraph, and if you're repurposing the paragraph to be a grid (and thus very not paragraph-like) then you might need to somehow tell Markdown this isn't an actual paragraph.

**Comment by nnsite** [comment]
> somehow tell Markdown this isn't an actual paragraph

Agreed ! Yes it's not really a footnote, is it, and it's not really a paragraph either.
I can use aria roles but markdown wouldn't care. 
Yet I found the solution: change the paragraphs into **lists**, like this:
```
- ![image](destination)
- ![image2](destination2)
- ![image3](destination3) 
{.center}
```
Clearer, and takes literally no more than 3 keystrokes to correct each item. Thanks for the inspiration. And my code is simpler too, no pesky fake-image span elements. Now it's so much cleaner.
