### ISSUE TITLE
How to use the header_id_func?

### ISSUE THREAD

**Issue by edent** [michelf/php-markdown#401]
I see in the code:

```php
	/**
	 * Optional header id="" generation callback function.
	 * @var callable|null
	 */
	public $header_id_func = null;
```

What value do I need to add there to transform `## Whatever` into  `<h2 id="whatever">Whatever</h2>`?

**Comment by michelf** [comment]
For this specific case, this would work:
```
$parser->header_id_func = "strtolower" // will call the strtolower function to generate the id
```
If you want to do something more (like replacing spaces with `_`) you can make your own function that does what you want. You can also write it as a closure:
```
$parser->header_id_func = function($string) {
    return str_replace(' ', '_', strtolower($string))
}
```
