### ISSUE TITLE
Markdown content inside `<details>` and `<summary>` elements is not rendered properly anymore

### ISSUE THREAD

**Issue by unsektor** [michelf/php-markdown#404]
Hello, since 1.9.1 version (see #329) markdown content inside `<details>` and `<summary>` elements is not rendered properly anymore, for example:

Source markdown code to be rendered:

````markdown
<details>
  <summary>**Test**</summary>

```html
<script>alert('Should not be executed, only displayed');</script>
```

</details>
````

Result HTML code after markdown rendering (**1.9.0**):

```html
<p>
    <details>
    <summary><strong>Test</strong></summary>
</p>
    <pre>
        <code class="html">&lt;script&gt;alert('Should not be executed, only displayed');&lt;/script&gt;</code>
    </pre>
<p>
</details>
</p>
```

Indeed, there is a bug that `<details>` element wrapped with `<p>` element, 
but markdown content inside `<details>` and `<summary>` elements is **rendered correctly**.

---

Result HTML code after markdown rendering (**1.9.1**):

````html
<details>
  <summary>**Test**</summary>

```html
<script>alert('Should not be executed, only displayed');</script>
```

</details>
````

After the changes, `<details>` element is not wrapped with `<p>` element anymore,
but markdown content inside `<details>` and `<summary>` elements is **not rendered correctly**.

At this moment i am not ready to submit either fix suggest or changes request, the temporary fix to avoid this behaviour is to downgrade **1.9.1** to **1.9.0**.

**Comment by th-h** [comment]
> Hello, since 1.9.1 version (see #329) markdown content inside `<details>` and `<summary>` elements is not rendered properly anymore, for example:

According to the [specification](https://michelf.ca/projects/php-markdown/extra/#markdown-attr), Markdown content in block level elements is only rendered if the block level element has an attribute `markdown="1"`.

> Source markdown code to be rendered:
> 
> ```
> <details>
>   <summary>**Test**</summary>
> 
> ```html
> <script>alert('Should not be executed, only displayed');</script>
> ```
> 
> </details>
> ```

This does work with 1.9.1:

    <details markdown="1">
      <summary>**Test**</summary>
    
    ```html
    <script>alert('Should not be executed, only displayed');</script>
    ```
    
    </details>

**Comment by unsektor** [comment]
Thank you for your quick response. I had not considered that.
This is a feature and not a bug, as it is part of the specification.
Therefore, I will close this issue.
