### ISSUE TITLE
Allow use within Namespaces

### ISSUE THREAD

**Issue by KellyLSB** [michelf/php-markdown#41]
Much of the parsing breaks in both markdown and markdown-extra when attempting to use within a namespace.

**Comment by wysman** [comment]
Agree with you, i use a framework with namespace and i have issue too.

PHP Warning:  preg_split(): Empty regular expression

**Comment by michelf** [comment]
Can one of you provide me with more details, or with a simple test case showing the problem? I haven't played with PHP namespace much yet, but calling Markdown from a namespace seems to work well for me, at least in this case:

```
<?php
namespace michelf\nstest;

require_once 'markdown.php';

echo Markdown("> *hello world*");

$p = new \Markdown_Parser;
echo $p->transform("> *hello world*");
```

**Comment by wysman** [comment]
Hi michelf,

I have made a fix, project fork is in progress.
I will make a merge request in few hours.

**Comment by wysman** [comment]
Pull request at https://github.com/michelf/php-markdown/pull/46

**Comment by michelf** [comment]
See the new [lib branch](https://github.com/michelf/php-markdown/tree/lib), namespace included. Right now, it's pre-release. Eventually, this'll probably become the default branch.
