### ISSUE TITLE
Blockquote fails to insert paragraphs inside it

### ISSUE THREAD

**Issue by rsgranne** [michelf/php-markdown#44]
I use this Markdown:

```
> Lorem ipsum
```

According to Gruber's example at [Dingus](http://daringfireball.net/projects/markdown/dingus), I should get this:

```
<blockquote>
  <p>Lorem ipsum</p>
</blockquote>
```

However, when I use the latest stable PHP Markdown Extra with both WordPress & Concrete5, I instead get this:

```
<blockquote>
  Lorem ipsum
</blockquote>
```

Needless to say, the absence of the P is problematic.

**Comment by michelf** [comment]
Can't reproduce this on the [PHP Markdown Dingus](http://michelf.ca/projects/php-markdown/dingus/). In what context does this happen?

**Comment by rsgranne** [comment]
I am using the Markdown On Save plugin with WordPress
(http://wordpress.org/extend/plugins/markdown-on-save/) & the built-in
Markdown add-on with the Concrete5 CMS
(http://www.concrete5.org/marketplace/addons/markdown/).

The Markdown On Save plugin came with this version of PHP Markdown Extra:

define( 'MARKDOWN_VERSION',  "1.0.1n" ); # Sat 10 Oct 2009
define( 'MARKDOWNEXTRA_VERSION',  "1.2.4" ); # Sat 10 Oct 2009

The Concrete5 Markdown plugin came with this (note that it wasn't even
PHP Markdown Extra, just PHP Markdown):

define( 'MARKDOWN_VERSION',  "1.0.1l" ); # Sun 11 May 2008

In both cases, I upgraded the files to the latest version of PHP Markdown Extra:

define( 'MARKDOWN_VERSION',  "1.0.1o" ); # Sun 8 Jan 2012
define( 'MARKDOWNEXTRA_VERSION',  "1.2.5" ); # Sun 8 Jan 2012

At that point, the errors showed up: paragraphs inside blockquotes
were stripped. Note that this occurred in both WordPress AND
Concrete5, even though the two systems are using different PHP
Markdown Extra files.

I downgraded to an older version in both WordPress and Concrete5:

define( 'MARKDOWN_VERSION',  "1.0.1n" ); # Sat 10 Oct 2009
define( 'MARKDOWNEXTRA_VERSION',  "1.2.4" ); # Sat 10 Oct 2009

This fixed the problem in WordPress & in Concrete5.

If you want more info or access, I can give it to you.

Scott

**Comment by michelf** [comment]
Can you give me the exact input, the text that gets filtered? Surely it's not really this

```
> Lorem ipsum
```

you wrote in your first post. I tried many variants without being able to reproduce it, and I can't figure out what has changed between those two versions that could cause something like this.

**Comment by rsgranne** [comment]
Hi, Michel. My apologies for not getting back to you in a timely manner. That was rude of me.

Yes, this …

```
> Lorem ipsum

> Lorem ipsum
```

… gets rendered as this …

```
<blockquote>

Lorem ipsum

Lorem ipsum

</blockquote>
```

… with the paragraphs stripped out.

I have upgraded PHP Markdown Extra to the latest version, & it’s still happening, at least in the latest WordPress with the Markdown On Save plugin for WordPress (http://wordpress.org/extend/plugins/markdown-on-save/).

**Comment by rsgranne** [comment]
If you need a log in to my server, I’m happy to provide what you need.

**Comment by michelf** [comment]
Well, that works fine in the [Dingus](http://michelf.ca/projects/php-markdown/dingus/), so I'd guess it's a problem with how Markdown On Save is integrating things into Wordpress. That, or a bad interaction with another Wordpress plugin.

You're saying it happens with Concrete5 too? If it happens in two places that's starting to look suspicious it might be in the Markdown parser.

Can you reproduce this in a more limited setup, like just a call to the Markdown function? Often, CMSs (and Wordpress in particular) have many other filters running before or after Markdown, which makes things hard to debug.

**Comment by rsgranne** [comment]
OK, here’s what's going on: I think it’s a problem with the WordPress plugin Markdown On Save not working with any version of PHP Markdown Extra after 1.2.4. I just filed a bug with him, which you can see at https://github.com/markjaquith/markdown-on-save/issues/3, & I’m awaiting his reply. Once I have that, I’ll follow up with you.

At this point, I’m not as sure about Concrete5. Let me investigate further.

**Comment by markjaquith** [comment]
Not an issue with PHP Markdown Extra — I'd apparently modified the file when I originally included it to remove the WordPress bits, instead of using the constants (or `$wp_version`) to disable those bits in PHP Markdown Extra. Bad past me.

This issue can be closed.

**Comment by michelf** [comment]
@markjaquith Great. Thanks for letting me know.
