### ISSUE TITLE
Code Block Languages

### ISSUE THREAD

**Issue by coreyworrell** [michelf/php-markdown#5]
It would be great define what language the code block is in. Just like how Github does it with its code blocks:

``````
``` ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
``````

or

```
~~~ php
class Whatever { }
~~~
```

**Comment by michelf** [comment]
Actually, this is what is planned for PHP Markdown Extra:

```
~~~ .php
class Whatever { }
~~~
```

The fenced code block syntax already exists, and the above would allow a class attribute to be specified on the code block.

**Comment by coreyworrell** [comment]
Yah, that's what I was talkin about. When do you think it will be implemented?
