### ISSUE TITLE
Interferes with Shortcodes

### ISSUE THREAD

**Issue by curtismchale** [michelf/php-markdown#54]
Use a shortcode that has 2 _'s and it won't work. See it with [edd_profile_editor] and we end up seeing profile in italics.

**Comment by michelf** [comment]
Sorry, but I can't fix this without reworking the Wordpress shortcode parser so it works directly inside PHP Markdown. As I'm not in the business of writing Wordpress, I'll decline.

For your specific problem, Markdown let you escape underscores by prefixing them with a backslahs, as in `\_`, which should make the shortcode work again. Or you can use PHP Markdown Extra instead which does not allow emphasis in the middle of a word using underscores.

**Comment by curtismchale** [comment]
Fair enough. Thanks for the work.
