### ISSUE TITLE
Support for classes on images

### ISSUE THREAD

**Issue by Svish** [michelf/php-markdown#57]
I see you have added support for classes on headers. Would be awesome to have a similar feature for images (and maybe links, since they're quite similar?). That way I could for example add left/right/center classes or other markers I could use either for styling with CSS or for finding with javascript.

**Comment by michelf** [comment]
That's a good idea. I'll add that to images when I have some time.

**Comment by scito** [comment]
Classes on images would be very helpful.

Height and width would also be useful. Especially in responsive design, as images can be preprocessed after the Markdown filter. Thus, smaller images could be sent to the client.

**Comment by brendo** [comment]
Being able to add classes to anchor elements would also be fantastic. eg (`.button` or `.cta`)

**Comment by michelf** [comment]
Done. Links and images. Will be part of the next release.

**Comment by tobiastom** [comment]
@michelf As you embed `IMG` tags into a `P` tag, I'm really confused why you would add the class to the image. If the class would be on the `p`, I could style both. With the class only on the `img` I don't have any chance of styling the `p`.

```
p.lala { background: black; }
p.lala img { border: 1px solid red; }
```
