### ISSUE TITLE
Update output for HTML5 (Lib branch)

### ISSUE THREAD

**Issue by michelf** [michelf/php-markdown#58]
Two things in the current output would need to be refreshed for HTML5. Here's what need to be done:
- **Footnotes**: Currently using the `rev` attribute for back-links. This attribute is no longer in HTML5. I'd suggest `rel="footnote-ref"`.
- **Tables**: Currently using the `align` attribute for cell alignment. This attribute is no longer in HTML5. I'm not sure what to suggest. Do we need to update this?

I'd like to fix these two before we get out of beta in the lib branch.

**Comment by waylan** [comment]
Regarding the footnotes, [this](https://github.com/waylan/Python-Markdown/commit/2fe5b5b5803c138f70e5c90aaa77f85f3c596f1d) is how I addressed it in Python-Markdown. See the commit message for an explanation.

**Comment by michelf** [comment]
@waylan `class=footnote-ref` and `class=footnote-backref` are indeed better. I forgot that HTML5 also restricted allowable values for the `rel` attribute.

**Comment by michelf** [comment]
Lib branch updated to use `footnote-ref` and `footnote-backref` classes in the output. a0724cd779872c603e81f17a76038f57db8f944f

**Comment by michelf** [comment]
Lib branch will keep using the `align` attribute for table cells, unless the user has set a class himself through the parser's configuration. This way with a default style sheet things will be aligned correctly and you'll still be able to affect the style though CSS using a selector matching it (`td[align="right"]`); using a `style="text-align:right"` attribute would make that difficult.
