### ISSUE TITLE
How to force only markdown syntax, don't allow regular html?

### ISSUE THREAD

**Issue by cnkt** [michelf/php-markdown#59]
Hi,

I don't want any regular html in my source text. Is there a way to force this?

For example, if source text includes <a href=""> tag, it should convert to &lt;a href=&quot;...

Thanks.

**Comment by michelf** [comment]
See http://michelf.ca/blog/2007/php-markdown-no-markup/

Also, be aware that this is [not a protection against XSS](http://michelf.ca/blog/2010/markdown-and-xss/).

**Comment by markseuffert** [comment]
Good to know, thanks!
