### ISSUE TITLE
_MarkdownExtra_TmpImpl does not respect PSR-0

### ISSUE THREAD

**Issue by moufmouf** [michelf/php-markdown#62]
Bonjour Michel,

Tout d'abord, un grand bravo pour la lib Markdown, et pour la migration vers Composer, c'est top.

A ce propos, je rencontre un tout petit problème, avec le chargement PSR-0.
Tu as mis la classe _MarkdownExtra_TmpImpl dans le fichier Markdown.php.
J'utilise MarkdownExtra.

Dans mon code, je fais:

``` php
$markdownParser = new MarkdownExtra();
```

L'autoloader de Composer trouve bien la classe MarkdownExtra, mais essaye ensuite d'autoloder  _MarkdownExtra_TmpImpl, et ne trouve pas cette classe.

J'ai trouvé un workaround tout simple: je fais:

``` php
// Force l'autoload:
$useless = new Markdown();

$markdownParser = new MarkdownExtra();
```

Néanmoins, ça serait super d'isoler la classe dans un fichier à part "PSR-0 complient".

**Comment by michelf** [comment]
La raison est de pouvoir facilement garder les changements synchronisés entre la branche Extra et la branche Lib. Pour que git fasse les merge correctement, il faut que je garde les deux implémentations dans le même fichier. C'est transitoire: je vais éventuellement tout remettre à la bonne place.

Ceci dit, ce n'est pas une raison pour que ça ne marche pas. J'ai corrigé le problème avec 06cb8f248746b8085c9757ab679c8aff629be719. Merci d'avoir rapporté le problème.
