### ISSUE TITLE
Add rel="external" on external links

### ISSUE THREAD

**Issue by bfontaine** [michelf/php-markdown#63]
For example with an option:

``` php
define( 'EXTERNAL_LINKS_REL_ATTR',  "external" );
```

It’s sometimes useful to add different styles on internal/external links (e.g.: `a[rel=external] {color:red}`).

This would add a `rel` attribute on every `<a>` element which begins with a protocol (`https://`, `http://`) or `//`.

So the converter would transform this:

``` markdown
[bar](foo), [google](http://www.google.com)
```

into this:

``` html
<a href="foo">bar</a>, <a href="http://www.google.com" rel="external">google</a>
```

**Comment by michelf** [comment]
I'm not going to add everyone's preferred transformation to PHP Markdown. This can be implemented as a post-processor taking the HTML output and adding `rel="external"` where needed.
