### ISSUE TITLE
Feature Request: Support for GitHub flavored markdown

### ISSUE THREAD

**Issue by ghost** [michelf/php-markdown#65]
I'm currently using this to preview my wiki changes on my local repository without the need to commit and push it to the GitHub repo. Works very well so far, except one thing: The GitHub syntax for including images differs from the "official" one. So, could you please add support for including images with `[[image.png]]`?
You could also add two configuration variables:
- `$enable_github_syntax` for enable/disable GitHub interpreting
- `$github_path` or something similar which defines the path of the GitHub wiki root.  
  Example: `$github_path` is set to `"/SomeRepo/wiki"`.  
  An image is included into a wiki page like that: `[[image.png]]`.  
  Now the `src`-tag should be `"/SomeRepo/wiki/image.png"`.

If you add this, previewing GitHub wikis offline would be _much_ easier.

**Comment by michelf** [comment]
My opinion on this is that Github's Markdown is different enough that it should be a separate parser, like the Markdown Extra parser is. If someone wants to implement GFM as a derived class, perhaps I will accept it as a pull request (that's not a commitment though). I'm not really interesting in doing that work.
