### ISSUE TITLE
Use public and private to make clear what the public API is

### ISSUE THREAD

**Issue by markushausammann** [michelf/php-markdown#66]
All your class methods are public, that's quite confusing. Please introduce privacy keywords so it becomes clear which methods are meant to be used by the class and which ones by the user.

**Comment by michelf** [comment]
The public API is the `transform` and the `defaultTransform` functions, plus the variables under the "Configuration Variables" comment at the beginning of the class. Also the `MARKDOWNLIB_VERSION` constant.

I'm currently transitioning form the older package model which is still compatible with PHP 4 (master and extra branches) to a PSR-0-compliant library package (lib branch) requiring PHP 5.3. I definitely plan to make most of the variables and functions protected for the lib branch once I stop maintaining the other two, but right now merging changes is easier if I don't.

But you're right that it's confusing. I'm keeping this open as a reminder that it must be done.

**Comment by localheinz** [comment]
Don't use `private`. Use `protected` instead.

**Comment by markushausammann** [comment]
Thanks for your answer and the great tool! Looking forward to this becoming a modern library, please also consider PSR-1 and 2. Meaning such things as one class per file only, etc.

Regarding private vs protected: At the moment, private will probably not do because people directly extend the class, so yes, protected. Futher development could go towards a private core and composition over inheritance by factoring the flexible parts out into separate classes and interfaces.

**Comment by localheinz** [comment]
:+1:

Looking forward to see the results!

**Comment by michelf** [comment]
@markushausammann @localheinz All the rest will indeed be protected. Protected members won't be part of the public API though: they're implementation details exposed so you can build your own parser on top of it, and the implementation may change from version to version so it's not necessarily something stable to build on. That needs to be clarified too.

**Comment by ghost** [comment]
Actually, the better thing to do is mark the API with `@API` annotation since both public and protected methods are considered API otherwise (`protected` because subclasses may/could rely on it unless otherwise informed...). Visibility by itself is not enough to mark API unless it's a private method, then it's clearly not. Sometimes things need to be public/protected but they are not meant to be public API and therefor not subject to BC. 

The best thing is to make everything private from the start and open up methods to being protected given use cases.

**Comment by michelf** [comment]
Ok. Added `public` and `protected` everywhere. `public` means part of the public API, `protected` means "use at your own risks". All this [explained in detail in the Readme file](https://github.com/michelf/php-markdown#public-api-and-versionning-policy), I think that'll be enough.
