### ISSUE TITLE
<footer> treated as a block level element breaks long existing markdown

### ISSUE THREAD

**Issue by simensen** [michelf/php-markdown#67]
1.0.1p broke my main style of formatting blockquotes when i want to attribute them to someone:

```
> for me the point of having my blog as a static site is mainly easy deployment<br>
> I don't have to worry about even configuring PHP<br>
> I just put html on a web server and boom! instant win
>
> <footer>— [Igor Wiedler wins](https://igor.io)</footer>
```

Are there some alternatives to getting this to render as expected or do I have to switch the way I do this sort of citation?

**Comment by michelf** [comment]
The old output (1.0.1o) was:

``` html
<blockquote>
  <p>for me the point of having my blog as a static site is mainly easy deployment<br>
  I don't have to worry about even configuring PHP<br>
  I just put html on a web server and boom! instant win</p>

  <p><footer>— <a href="https://igor.io">Igor Wiedler wins</a></footer></p>
</blockquote>
```

The new output (1.0.1p) is:

``` html
<blockquote>
  <p>for me the point of having my blog as a static site is mainly easy deployment<br>
  I don't have to worry about even configuring PHP<br>
  I just put html on a web server and boom! instant win</p>

  <footer>— [Igor Wiedler wins](https://igor.io)</footer>
</blockquote>
```

I'd guess that neither of them is really what you want, because `<footer>` appearing inside of `<p>` is not valid HTML.

The new behaviour better conforms to Markdown rules in the sense that it does not parse the content of an HTML block elements. If you were to start a paragraph with a `<p>` tag for instance, the content of that paragraph wouldn't be parsed by Markdown.

Still, that was before those new HTML elements existed, so perhaps we should do something different with them. Hum...

**Comment by simensen** [comment]
Yeah, the old output wasn't 100% correct. :) But it was far closer to what I was looking for. ;) I don't think I had noticed the <p> wrapping <footer> before. I sure noticed when all of my citations stopped rendering as links, though.

Happy to help thin this through with you, though I'm sure I may just have to recode my stuff. It would be a shame to have to manually create <a> links but it might be the safest thing to do at this point.

I just migrated my static site generator off of my dflydev/markdown package to michelf/php-markdown because my initial tests showed that everything was parsing correctly. I guess I didn't look closely enough. :( My blog ( http://srcmvn.com ) currently has a lot of these little bits of footer links broken.

Thanks for the quick response. :)

**Comment by michelf** [comment]
I decided I'm not going to “fix” this. `<footer>` is a block-level element and is treated as such (no formatting inside), which is the correct thing to do. The solution is to use PHP Markdown Extra, which has the `markdown="1"` attribute, but I acknowledge issue 68 makes it difficult in this context.

**Comment by simensen** [comment]
I don't really see any other way around it besides `markdown="1"` if this isn't something that can be "fixed." I'll give that a try. I'd just as soon not have to doctor my HTML tags but I guess this isn't too terrible. Thanks. :)
