### ISSUE TITLE
Underscore between words converts it to italic

### ISSUE THREAD

**Issue by umeshk** [michelf/php-markdown#70]
Hi Guys,

I am using Markdown since 2-3 years. It is very useful tool. But I am facing strange issue that if I write this "I am a very hard_soft person here_there only". Then it converts italic letters from soft to here i.e. "soft person here" will be all in italic and all other are in normal format. But I do not want to those letters to be italic still I want underscore over there.

Is there any workaround for this?
Looking for solution.

Thanks in advance.

**Comment by michelf** [comment]
This is standard Markdown syntax. You can escape (prefix with a backslash) underscores to avoid that.

Or you can try PHP Markdown Extra instead, it disallows underscore as emphasis when in the middle of a word.

**Comment by umeshk** [comment]
Thanks Michelf.
I have got the latest one from here https://github.com/symphonycms/markdown/blob/master/lib/php-markdown-extra-1.2.6/markdown.php. I will be using PHP Markdown Extra.

Just wondering will there be any issue if I use PHP Markdown Extra. I mean to say are all functions present in PHP Markdown Extra.

**Comment by michelf** [comment]
Underscore-emphasis is the only feature from Markdown that works differently in Extra, notwithstanding potential bugs. It's slightly slower to process too, but you probably won't notice.
