### ISSUE TITLE
Metadata support in documents

### ISSUE THREAD

**Issue by seyDoggy** [michelf/php-markdown#71]
Similar to MultiMarkdown I would love to see meta data parsed. So that this syntax (for example) found at the top of a document:

``` text
Title: Some page title
Description: The best site in the world.
Keywords: cute, kittens, lulz
```

Would be parsed as:

``` html
<title>Some page title</title>
<meta name="description" content="The best site in the world.">
<meta name="keywords" content="cute, kittens, lulz">
```

**Comment by michelf** [comment]
I don't think this belongs in PHP Markdown. PHP Markdown parses text and outputs HTML content, not whole documents.

I'd recommend this be implemented as a separate pre-filter. Such a filter could be made agnostic to whatever syntax you decide to use below (be it Markdown, Textile, or something else).

**Comment by seyDoggy** [comment]
Yes good point. Maybe I'll make one.  

## 

Adam Merrifield
seyDoggy vCard: seyDoggy.com/vcard
