### ISSUE TITLE
clear method

### ISSUE THREAD

**Issue by galactics** [michelf/php-markdown#76]
Create a clear method in order to remove any markdown-related text.

Although not mandatory, this could be useful when dealing with abstracts (first n words of an article for instance).

**Comment by michelf** [comment]
At first glance, I don't think this belongs in PHP Markdown. Is there anything a Markdown parser can do better than a script filtering the resulting HTML? An example would be welcome.

**Comment by michelf** [comment]
Closing due to lack of feedback.
