### ISSUE TITLE
Header/comment conflict - needs update?

### ISSUE THREAD

**Issue by wontonst** [michelf/php-markdown#78]
<b>NOTE: this error appears to be fixed in markdown extra 1.2.6 downloaded from your website @ michelf.ca</b>

The error is that md that looks like

```
<pre>
#title 
</pre>
```

outputs
# title in h1 format within a code block. which makes no sense.

doing

<pre>
\#title
</pre>

works around this issue.

I'm pretty sure you just need to update this repo.

**Comment by michelf** [comment]
Properly closing your `<pre>` with a `</pre>` also fixes the issue. You wrote two unterminated `<pre>` tags and PHP Markdown doesn't really know what to do with them.

**Comment by wontonst** [comment]
My bad, the code was not copy pasted, edited.

**Comment by michelf** [comment]
I wonder still why you say I need to update this repo... I just saw that I forgot to update the _extra-stable_ branch (done now). Is this what you're referring to? Or if you're seeing this with the _extra_ branch it's likely a regression introduced after the release. In any case it'd help me if you could tell me what you tried exactly.
