### ISSUE TITLE
Allow reverse (html2markdown)

### ISSUE THREAD

**Issue by didacrios** [michelf/php-markdown#79]
I may asking for an obvious thing, but i could not found.

Is there a way to convert the html to markdown with this class? How?

If it's not, could be a nice feature to implement as we are talking about php, so we can edit messages in the markdown mode without having to save the raw text in the database

**Comment by michelf** [comment]
See http://milianw.de/projects/markdownify/

Be aware however that you won't get the same Markdown input as you had before. There's many ways in Markdown to write the same HTML document. The better way is to save the Markdown version next to the HTML one an reuse it when editing.
