### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by vadviktor** [michelf/php-markdown#8]
Hello!

I thank you for the code you have written so far, though at the time of writting this notice for you I could not get it to work. As I have started to debug the problem, I have came accross a dozen of unused variables here-and-there. Some of them are 'trapped' in conditional statements, some are lonely function parameters. I suggest you revise your code with some sophisticated IDE like PHPStorm. (I do not know any code quality checking scripts as of yet, sorry)

Hope my notice will help you correct your code and eliminate some more bugs.

Cheers!

**Comment by michelf** [comment]
This report would be more useful if it included the list of unused variables. Or even better, you can correct it yourself and send me a pull request.

I'm more interested however in why you can't make it to work... unused variables are mostly insignificant compared to that.

**Comment by jjok** [comment]
PHP Mess Detector is good for finding unused variables and methods.

https://github.com/phpmd/phpmd

I ran it with just the 'unusedcode' rule and it came up with these issues:
- markdown.php:177  Avoid unused parameters such as '$noimage'.
- markdown.php:261  Avoid unused local variables such as '$in_anchor'.
- markdown.php:305  Avoid unused local variables such as '$priority'.
- markdown.php:573  Avoid unused local variables such as '$priority'.
- markdown.php:630  Avoid unused local variables such as '$priority'.
- markdown.php:643  Avoid unused parameters such as '$matches'.
- markdown.php:753  Avoid unused local variables such as '$whole_match'.
- markdown.php:857  Avoid unused local variables such as '$whole_match'.
- markdown.php:930  Avoid unused local variables such as '$marker_any_re'.

**Comment by michelf** [comment]
The `$in_anchor` was a bug. All others are checked and are harmless. Closed.
