### ISSUE TITLE
[link](<s p a c e s>)

### ISSUE THREAD

**Issue by michelf** [michelf/php-markdown#80]
A link like this one:

```
[link](<s p a c e s>)
```

should work, because of the angle-brackets.

Also, it works in Markdown.pl.

**Comment by michelf** [comment]
Issue seems to be with the HTML tag parser that runs before the link and interprets `<s` as the start of a tag. It doesn't happen with `<http://blah>` because it is not recognized as a HTML tag.

The only viable solution to this would be to fold `doAnchor` within `parseSpan`.

**Comment by funivan** [comment]
i test it right now and i`s ok

```
[link0](<s p a c e s>)
[link2](<s%20p%20a%20c%20e%20s%20>)
```

Try =)

**Comment by michelf** [comment]
No it's not. `[link0](<s p a c e s>)` should output `<a href="s p a c e s">link0</a>` not `<a href="<s p a c e s>">link0</a>`.
