### ISSUE TITLE
Built-in XSS protection

### ISSUE THREAD

**Issue by xPaw** [michelf/php-markdown#82]
It would greatly simplify using this library, without anything extra.

**Comment by xPaw** [comment]
Alternatively, it would be good enough to only parse links if they start with allowed protocol (http, https, mailto)

**Comment by michelf** [comment]
XSS is a tricky subject.

First, not everyone wants an XSS filter. I use the parser my website and if I want to include a bit of Javascript it has to pass through. It's probably very common to want to do that to embed, say, a video from Youtube, or special things copy-pasted from elsewhere. That's the whole reason Markdown supports HTML in the input.

So the XSS filter would have to be a separate mode, or an add-on of some sort. At that point, it's not harder to have a separate XSS filter that you just chain after Markdown, as in `$html = xss_filter(Markdown($text))`.

And XSS is surprisingly tricky to catch given how strangely some browsers interpret malformed tags and URLs. Better leave that task to a tool made specifically for that purpose. For instance: [kses](http://sourceforge.net/projects/kses/).

**Comment by xPaw** [comment]
I disabled html markup, but there's a possibility to xss via link tag. I
think protocol filter should be a reasonable feature.

**Comment by michelf** [comment]
Assuming I'd be willing to add a `no_xss` mode (whatever the name), I wouldn't be comfortable claiming it can prevents XSS without a thorough review of the whole code base, and probably some refactoring, which would take a lot of time.

On the other hand, if you want a callback to filter/change URLs in links, that's actually a feature that'd be useful in many contexts, feel free to create an issue for that (or better, a pull request). But I don't see myself adding a filter for XSS anytime soon. Specialized filters exists for that that'll catch even things a bug in the Markdown parser might have let through.
