### ISSUE TITLE
Tables not work for me...

### ISSUE THREAD

**Issue by hedcler** [michelf/php-markdown#86]

**Comment by Avalarion** [comment]
Are you using markdown or markdown extras? http://michelf.ca/projects/php-markdown/extra/ This is an important question. Also it would be very nice to have a little bit more of text or description when opening an issue.

1.) What is your prerendered source text?
2.) What is your PHP?
3.) Are you sure, that this is an issue and not wrong usage?

Have a nice day,

Bastian

**Comment by hedcler** [comment]
I download this library now... My code is:

```
<?php 
    $md = file_get_contents('index.md');
    include 'markdown/Markdown.php';
    echo \Michelf\Markdown::defaultTransform( $md );
```

**Comment by hedcler** [comment]
And MarkdownExtra class is: 

```
class MarkdownExtra extends \Michelf\_MarkdownExtra_TmpImpl {

    ### Parser Implementation ###

    # Temporarily, the implemenation is in the _MarkdownExtra_TmpImpl class.
    # See note above.

}
```

in this version...

**Comment by hedcler** [comment]
Thanks @Avalarion ! I change to this:

```
echo \Michelf\_MarkdownExtra_TmpImpl::defaultTransform( $md );
```

And all work now! :smile:

**Comment by Avalarion** [comment]
Perfect =).

**Comment by michelf** [comment]
`\Michelf\Markdown` is the base Markdown parser (no tables).

`\Michelf\MarkdownExtra` is the Markdown Extra parser (has tables).

Currently, `\Michelf\MarkdownExtra` is implemented as a subclass of `\Michelf\_MarkdownExtra_TmpImpl` (found in the Markdown.php file), but that's a temporary implementation detail you should not care about. In time, the `_MarkdownExtra_TmpImpl` class will disappear and only `\Michelf\MarkdownExtra` will remain. I wish I could make that temporary class private to the Michelf package...
