### ISSUE TITLE
Wrong format of conversion

### ISSUE THREAD

**Issue by sidealice** [michelf/php-markdown#95]
Original:

这是一个普通段落。

<table>
    <tr>
        <td>Foo</td>
    </tr>
</table>

这是另一个普通段落。
adfasdfads

werw

EOF

Result:

<p>这是一个普通段落。</p>

<table>
    <tr>
        <td>Foo</td>
    </tr>
</table>

<p>这是另一个普通段落。
adfasdfads</p>

<p>werw</p>

<p>EOF</p>

I noticed that the line 'adfasdfads' should be another <p> pair , why they combined together with previous line?

**Comment by michelf** [comment]
The Markdown syntax says that you need to insert two spaces to have a line break. Reference: http://daringfireball.net/projects/markdown/syntax#p
